### ISSUE TITLE
Improve copyright section

### ISSUE THREAD

**Issue by rtewari056** [Arun9739/Paryatana#102]
**Is your feature request related to a problem? Please describe.**
There should be a developer profile link attached with the developer name in the copyright section.

**Describe the solution you'd like**
When a user click on the name, it will redirect to the LinkedIn/GitHub profile of the developer.

**Screenshots**

![improve](https://user-images.githubusercontent.com/75976169/194105433-efc1a574-0851-4a02-8253-be6d62733f1f.png)

**Comment by Arun9739** [comment]
@rtewari056 Go ahead
Redirect it to my linkedin page : www.linkedin.com/in/arun-g-nayak

Star the repo ⭐ to show your love.
