### ISSUE TITLE
Add Trendy Card Design

### ISSUE THREAD

**Issue by aniketsinha2002** [Arun9739/Paryatana#104]
**Is your feature request related to a problem? Please describe.**
Add Trendy Card Design

**Describe the solution you'd like**
Want to change the basic card's design to a new trendy card design.

**Screenshots**
![image](https://user-images.githubusercontent.com/97850511/194110829-e84bdd14-a006-43b0-902b-642ee0c42f5c.png)

**Comment by Arun9739** [comment]
Go ahead @aniketsinha2002 
Show the love by starring the repo 🌟
