### ISSUE TITLE
Want to fix the responsiveness of tour package cards

### ISSUE THREAD

**Issue by swastik-bose007** [Arun9739/Paryatana#105]
*What is the bug**
**The tour cards in home page are not responsive in the width range 600px to 1000px**

**Expected behavior**
Tour cards should be either in col-6 col-6 form in tablet view or col-12 both.

**Screenshots**
![image](https://user-images.githubusercontent.com/98341839/194114462-26fdb3b1-dcfa-4cb5-a20a-1eb3f8308797.png)

**Comment by Arun9739** [comment]
Good catch @swastik-bose007 
Go ahead 👍 
Show your support by starring the repo 🌟

**Comment by Arun9739** [comment]
@swastik-bose007 If you want to work again on this issue you will be given 2 days time.
Else this issue will be assigned to someone else.

**Comment by Arun9739** [comment]
Anyone can take up this issue.

**Comment by Aakash67** [comment]
I would like to work on this issue

**Comment by Arun9739** [comment]
@Aakash67 Go ahead
Str the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@Aakash67 Plz finish the task early.

**Comment by Arun9739** [comment]
@Aakash67 Due to inactivity this issue will be unassigned.
Anyone can take up this issue.

**Comment by Dheerajjha451** [comment]
Assigned me this @Arun9739

**Comment by Arun9739** [comment]
@Dheerajjha451 Go ahead
Star the repo ⭐ to show your support.
