### ISSUE TITLE
Properly organizing copyright section

### ISSUE THREAD

**Issue by moinmulla** [Arun9739/Paryatana#106]
**Is your feature request related to a problem? Please describe.**
There should be proper spacing ,new line for creator's name,social media links with it's icons and little bit bigger area for copyright section

**Describe the solution you'd like**
Properly organize the copyright section that would be eye catching for the user.

**Comment by Arun9739** [comment]
@moinmulla Thank you for your interest
But this issue is already present and has been assigned to someone else
Plz look for other issue or create new issue

Show your support by stargazing the repo 🌟
