### ISSUE TITLE
Customizing the buttons in the home screen

### ISSUE THREAD

**Issue by itzwow** [Arun9739/Paryatana#107]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Adding border radius to the buttons in the home screen to make the UI better

**Screenshots**
![issue1](https://user-images.githubusercontent.com/84179065/194127397-08c1c5b6-8036-4abf-969f-aebda714ec00.JPG)

**Comment by Arun9739** [comment]
Go ahead @itzwow 
Plz apply the effect to all the possible buttons such as book now, check now etc, in all tthe pages

Star the repo 🌟 to showcase our love
