### ISSUE TITLE
Adding social media buttons to Image slider in About us page

### ISSUE THREAD

**Issue by asphalke07** [Arun9739/Paryatana#11]
**Is your feature request related to a problem? Please describe.**
One must be able to redirected to social media accounts when the buttos are being clicked.

@Arun9739

**Comment by Johnoris** [comment]
Assign this to me I'll love to fix it

**Comment by Johnoris** [comment]
Also leave the name of the social media handles

**Comment by abhishekpatil4** [comment]
@Arun9739 Assign me this issue. I'm a full-stack developer (MERN Stack). HTML CSS JS NodeJs ExpressJs Bootstrap Figma Tailwindcss

**Comment by Arun9739** [comment]
Go ahead @asphalke07 

Please redirect to : 
Twitter - https://twitter.com/arunnayakg7
For other social media coounts just redirect it to respective social media websites.

Show your love by starring the repo 🤩

**Comment by Arun9739** [comment]
@Johnoris and @abhishekpatil4 please look for other issues or create your own issues
Thank for your interest
Show your love by starring the repo 🌟
