### ISSUE TITLE
Fade on Scroll Animation

### ISSUE THREAD

**Issue by MridulTi** [Arun9739/Paryatana#111]
## Is your feature request related to a problem? Please describe.**
The way the content is presented on the website right now is relatively static,
#### A clear and concise description of what you want to happen.
I would Like to add a fade-in animation on the contents on scroll, as in when the user will scroll towards that content, the content will appear with a bit of fade-in and rise up animation or a Reveal Animation, it will help to retain the user's attention on the content more,
**Screenshots**
### Website Right Now :
![image](https://user-images.githubusercontent.com/92802892/194203142-33f377e6-ad16-41b0-a716-ceaf31e58566.png)

### an example of the kind of animation I am aiming for
https://codepen.io/SitePoint/pen/warKXE

If you like the idea then please assign this issue to me!

**Comment by Arun9739** [comment]
Go ahead @MridulTi 
Show your support by stargazing the repo 🌟
