### ISSUE TITLE
styling images radius

### ISSUE THREAD

**Issue by nipun-das** [Arun9739/Paryatana#113]
A slight change in border-radius can improve the UI.
Kindly assign me the issue so that I can work on the project.

**Comment by Arun9739** [comment]
@nipun-das Go ahead
Change the border of all possible images

Star the repo ⭐ to show your support

**Comment by Arun9739** [comment]
@nipun-das Plz finish the task early

**Comment by Arun9739** [comment]
@nipun-das Due to inactivity this issue will be closed.
