### ISSUE TITLE
Creating Code of Conduct

### ISSUE THREAD

**Issue by Mohammed-Shoaib01** [Arun9739/Paryatana#117]
**Is your feature request related to a problem? Please describe.**

I was hoping to contribute the code of conduct for this repository, please assign if possible!

**Describe the solution you'd like**

To create a code of conduct

**Comment by Arun9739** [comment]
Go ahead @Mohammed-Shoaib01 
Try to make it more professional
Show you suport by stargzing the repo 🌟

**Comment by Mohammed-Shoaib01** [comment]
Okay!
