### ISSUE TITLE
Misspell of Website name on Contact Us page

### ISSUE THREAD

**Issue by asphalke07** [Arun9739/Paryatana#12]
*What is the bug**
There seems misspell of Navbar Brand name in Contact Us page. 

**Expected behavior**
On Contact Us page , website name should be shown Paryatana but it is displayed as Parytana

**Screenshots**
![image](https://user-images.githubusercontent.com/78165094/193555890-ea1f1103-3e2f-4592-b50e-9ef3c315089f.png)

**Comment by Sas2k** [comment]
Hello @Arun9739, Would you mind Assigning me this issue please.
I'm a Hobbyist Full-Stack Developer.

**Comment by kanishk6103** [comment]
> _What is the bug_* There seems misspell of Navbar Brand name in Contact Us page.
> 
> **Expected behavior** On Contact Us page , website name should be shown Paryatana but it is displayed as Parytana
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/78165094/193555890-ea1f1103-3e2f-4592-b50e-9ef3c315089f.png)

I already fixed it with the navbar issue #18

**Comment by Sas2k** [comment]
nice.

**Comment by Arun9739** [comment]
Go ahead @asphalke07 
Show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@abhishekpatil4, @Sas2k, @kanishk6103 please look for new issues or create your own issues.
Thank for your interest 😃 
Show your love by starring the repo 🤩

**Comment by Arun9739** [comment]
@asphalke07 As this issue was resolved by someone else under some other issue number, this issue will be closed.
Please look for other issues or create new issue.
