### ISSUE TITLE
Images in readme file

### ISSUE THREAD

**Issue by harshpoddar03** [Arun9739/Paryatana#120]
**Describe the solution you'd like**
add screenshots of the website in the readme file

**Screenshots**
![image](https://user-images.githubusercontent.com/99535640/194289631-91698bec-d922-483c-8c70-a26e8d9a079d.png)

**Comment by tussharpaul13** [comment]
> **Describe the solution you'd like** add screenshots of the website in the readme file
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/99535640/194289631-91698bec-d922-483c-8c70-a26e8d9a079d.png)

May I add screenshots??
