### ISSUE TITLE
Navbar Design and Overall page design

### ISSUE THREAD

**Issue by Elu007** [Arun9739/Paryatana#122]
Hello, I have some awesome design ideas with the latest bootstrap 5.1, so if you assign me this task I can make changes for a better look for this website.

**Comment by Elu007** [comment]
Thank you for the assignment, I will work on that thank you.

**Comment by Arun9739** [comment]
@Elu007 Plz finish your task early

**Comment by Arun9739** [comment]
@Elu007 Due to inactivity this issue will be closed.
