### ISSUE TITLE
want to edit these cards and fix favicon bug

### ISSUE THREAD

**Issue by 17rashi** [Arun9739/Paryatana#124]
Your cards in the about section are extra vibrant, I want to fix its CSS and will add social media icons.
![image](https://user-images.githubusercontent.com/87816619/194324096-85636f22-e86f-435f-997c-1a99fb003c45.png)

one more thing, In the last issue, I requested the logo. check yours and mine, ones. (Let me know if you like it.)
![White Simple Travel Logo](https://user-images.githubusercontent.com/87816619/194324424-d0e758d1-720f-4884-aa98-d7846b0614c3.png)

**Favicon is only visible on home page, but when I redirect to some other pages, its not visible these, so I will edit it**

**Comment by Arun9739** [comment]
@17rashi The issue related to cards and logo are already present
If you want to work on the favicon issue plz create new issue for that only

Show your support by stargazing the repo 🌟
