### ISSUE TITLE
Change in mouse effect in about section

### ISSUE THREAD

**Issue by Rancho2002** [Arun9739/Paryatana#125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In the about section, it is better if there is a transition and some hover effect in 'who we are' section. 

**Screenshots**

https://user-images.githubusercontent.com/92109154/194348102-924467ab-9be4-42db-b3d3-970d0492c17e.mp4

**Comment by Rancho2002** [comment]
@Arun9739 pls assign me the task

**Comment by Arun9739** [comment]
Go ahead @Rancho2002 
Show your suuport by stargazing the repo 🌟

**Comment by albetros24** [comment]
kindly allow me to resolve this issue

**Comment by Arun9739** [comment]
@Rancho2002 and @albetros24 Thank you for your interest
But this issue is already present and has been assigned to someone else
Plz look for other issues or create new issues
