### ISSUE TITLE
Scroll To Top Button

### ISSUE THREAD

**Issue by Swastik1710** [Arun9739/Paryatana#13]
**Is your feature request related to a problem? Please describe.**
As of now, if a user wants to go to any other section with the help of navbar links, they have to scroll back entirely to the top of the page.
**Describe the solution you'd like**
I'd like to add a Scroll to Top button to each page so that the users can get back to the start of the page directly without having to scroll.

**Screenshots**

**Comment by Swastik1710** [comment]
Please assign it to me, so that I can start working on it.

**Comment by abhishekpatil4** [comment]
@Arun9739 Assign me this issue. I'm a full-stack developer (MERN Stack). HTML CSS JS NodeJs ExpressJs Bootstrap Figma Tailwindcss

**Comment by Arun9739** [comment]
Go ahead @Swastik1710 
Please show your love by starring the repo 🤩

**Comment by Arun9739** [comment]
@abhishekpatil4 Thank for your interest
Please look for other issues or create your own issues 
Show your love by starring the repo 🤩

**Comment by Swastik1710** [comment]
> Go ahead @Swastik1710 Please show your love by starring the repo 🤩

Thanks @Arun9739, I'll get to it.
