### ISSUE TITLE
Improper copyright section of CONTACT page 

### ISSUE THREAD

**Issue by moinmulla** [Arun9739/Paryatana#133]
*What is the bug**
Copyright section of CONTACT page is not synchronize.

**Expected behavior**
All the pages must have same copyright section

**Screenshots**
![image](https://user-images.githubusercontent.com/65023937/194398487-e336f1d8-3cc3-4d1c-a7f0-15ebaba2fa45.png)

**Comment by moinmulla** [comment]
Improper copyright section of CONTACT page which is not synchronize with other

**Comment by moinmulla** [comment]
Assign me this issue I can improve it and make proper.

**Comment by Arun9739** [comment]
@moinmulla Thank you for your interest
But this issue is alreday present and has been assigned to someone else

Show your suport by stargazing the repo 🌟
