### ISSUE TITLE
Improve who we are cards on about page

### ISSUE THREAD

**Issue by Trust-007** [Arun9739/Paryatana#135]
I would love to add a transition effect on the cards in this section. In my opinion the hover effect is too rigid and unappealing. I would like to give it a transition which would make it more user appealing.
![Screenshot (24)](https://user-images.githubusercontent.com/72111684/194404885-07e0da55-3a06-4dd1-8edc-820ba6fc7f29.png)

**Comment by Trust-007** [comment]
Please assign this issue to me so i can work on it 🙏 😄

**Comment by heysaiyad** [comment]
Please assign this work to me, bcoz I am a front end developer so I will make it very attractive page.

**Comment by Arun9739** [comment]
Go ahead @Trust-007 
Plz make the better looking effect
Sorry for delay to assign

Show your love by stargaing the repo 🌟

**Comment by Arun9739** [comment]
@priyank003 and @heysaiyad Please look for other issues or create new issues
Show your support by stargazing the repo 🌟

**Comment by Trust-007** [comment]
Thanks @Arun9739 i'll work on it.

**Comment by Arun9739** [comment]
@Trust-007 Due to inactivity and the issue is proposed by someone else, this issue will be closed
Thank you 👍
