### ISSUE TITLE
Footer of contact page has not been styled

### ISSUE THREAD

**Issue by pandeatul27** [Arun9739/Paryatana#138]
*What is the bug**
The footer of contact page has not been styled and is missing other information
**Expected behavior**

**Screenshots**
<img width="960" alt="2022-10-07 (1)" src="https://user-images.githubusercontent.com/94844506/194470510-58657fb5-36c5-4697-bd72-44f27ddcb760.png">
**Additional context**

**Comment by pandeatul27** [comment]
Allow me to work on this issue under hacktoberfest

**Comment by tanvigarg264** [comment]
Hi! I can work upon this.

**Comment by heysaiyad** [comment]
sir I am a Front end developer . You give me a chance I will make it very attractive web pages.

**Comment by Arun9739** [comment]
@pandeatul27, @tanvigarg264, @heysaiyad  Thank you for your interest
But this issue is already present and has been assigned to someone else.

Plz look for other issues or create new issues

Star the repo 🌟 to showcase your love.
