### ISSUE TITLE
Wants to add more favourite places

### ISSUE THREAD

**Issue by KAMYAVERMA** [Arun9739/Paryatana#145]
** Wants to add more favourite places in favourites.html page **

It is basic rn, will make it creative.
Kindly, allow me work on this.

![Screenshot 2022-10-08 013324](https://user-images.githubusercontent.com/85511676/194644267-9e45d701-134c-44a5-84a5-ea8060b09be0.jpg)

HAPPY HACKING.

**Comment by Arun9739** [comment]
Go ahead @KAMYAVERMA 
Add some creativity over there.

Show your love by stargazing the repo 🌟

**Comment by KAMYAVERMA** [comment]
Thankyou!
