### ISSUE TITLE
Wants to add footer to the footer page

### ISSUE THREAD

**Issue by albetros24** [Arun9739/Paryatana#146]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Screenshots**

**Comment by albetros24** [comment]
Kindly allow me to add footer  to your  contact now page   maintaining   same theme as  in the rest of the pages

**Comment by ksba2004** [comment]
@Arun9739 can I work on this? I do have a good knowledge of HTML, CSS, etc.

**Comment by mahitha09** [comment]
@Arun9739 Hi Arun, Can you please assign this to me and allow me to work on this issue? You can have a look at my profile for more info. Thanks:)

**Comment by Arun9739** [comment]
@mahitha09, @ksba2004, @mahitha09 Thank you for your interest
But this issue is already present
So try to make new issues or look for other issues

Show your love by starring the repo 🌟
