### ISSUE TITLE
Improving Icon style in footer section

### ISSUE THREAD

**Issue by Proder** [Arun9739/Paryatana#150]
Please assign this issue to me...I will do it for you.

**Comment by creater-shikha** [comment]
assign this issue to me

**Comment by Arun9739** [comment]
Go ahead @Proder 
Plz star the repo 🌟 to show your love.

**Comment by Arun9739** [comment]
@creater-shikha plz create new issues or look for other issues present.
Show your love by stargazing the repo 🤩

**Comment by Arun9739** [comment]
@Proder plz finish yiur task early.
