### ISSUE TITLE
Hover Effect On Tour Packages In Home & Tour Page

### ISSUE THREAD

**Issue by 1tsak** [Arun9739/Paryatana#151]
**Add smooth scale effect while hovering on tour packages on the home and tours page**

*Description*
 The tour packages on the home and tours page should scale up on hover with a smooth transition.

**Screenshots**
![image](https://user-images.githubusercontent.com/42407874/194568548-fc3273ef-4a80-48bd-b980-d5e2a1434faa.png)

**Comment by Arun9739** [comment]
@1task Go ahead
Star the repo 🌟 to show your love.

**Comment by 1tsak** [comment]
Thankyou, Starred Already👍
