### ISSUE TITLE
Places you must visit cards and check now box

### ISSUE THREAD

**Issue by Mysterious786** [Arun9739/Paryatana#152]
Hovering over the cards of **places you must visit the background **is becoming a lot shadowy along in the background with a little bluey at  border also the text inside it is very shinny that becomes little blurry  when the cursor is over the card.
The checknow and other two location boxes should be aligned properly since it just looking like the images are pasted over the banner . 

![Screenshot (103)](https://user-images.githubusercontent.com/110441918/194711079-efb45e1e-5577-4254-baaa-a874beb795bd.png)

**Comment by Arun9739** [comment]
Go ahead @Mysterious786 
Show your love by stargazing the repo 🤩

**Comment by Mysterious786** [comment]
I will do my best.

**Comment by Arun9739** [comment]
@Mysterious786 Plz finish the task early
