### ISSUE TITLE
Adding box shadow to places cards

### ISSUE THREAD

**Issue by goldenPheonix02** [Arun9739/Paryatana#154]
**Describe the solution you'd like**
Adding a pretty box shadow to the places card and also increasing the shadow a bit on hover

**Screenshots**
![image](https://user-images.githubusercontent.com/75632793/194714790-a40dad3a-878e-47bb-b7d2-4fa383a955af.png)

**Comment by goldenPheonix02** [comment]
can i work on this?

**Comment by rajatrai30** [comment]
assign this task to me. i can easily do

**Comment by Arun9739** [comment]
@goldenPheonix02 Go ahead
Show your support by stargazing the repo 🤩

**Comment by Arun9739** [comment]
@rajatrai30 Look for other issues or create new issues
Star the repo ⭐ to showcase your support
