### ISSUE TITLE
social links bug on contact section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [Arun9739/Paryatana#157]
*What is the bug**
The icons of social links is not showing in contact section as well as I think there is no need to add it as in footer section,the links are already present.
**Expected behavior**
I think removal of those social links should be appropriate solution as the footer section already address that problem.
**Screenshots**
![image](https://user-images.githubusercontent.com/110082824/194716003-5bc91bc9-c736-46a4-aac0-5a12c71a6593.png)

**Additional context**

**Comment by LoganArnett** [comment]
I created a PR in relation to this issue

**Comment by AryanSahoo-2003** [comment]
> I created a PR in relation to this issue

Bro ,I don't think it is fine to use other's issue to do a PR even before getting assigned...as I also waited for getting it assigned to me before doing a PR😶

**Comment by Arun9739** [comment]
Go ahead @AryanSahoo-2003 
Do the needful changes
Show your support by stargazing the repo ⭐

**Comment by AryanSahoo-2003** [comment]
Sir! I have made the PR ...please check that in open pull request section
