### ISSUE TITLE
Add a section of satisfied customers (reviews)

### ISSUE THREAD

**Issue by emepuchades** [Arun9739/Paryatana#16]
**Is your feature request related to a problem? Please describe.**
A section is missing where you can see the good reviews of the people who have the travel services on your website.

**Describe the solution you'd like**
On the homepage you could add a part of reviews

**Screenshots**

**Comment by navya-Singla-1-3-0-9** [comment]
Can you please assign this issue to me?

**Comment by emepuchades** [comment]
If you want, you can assign the issue

**Comment by Arun9739** [comment]
@emepuchades Thank you for your interest
But the reviews are present under testimonial in about section
You can update that tesimonial section by creating new issue

Show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@emepuchades, @navya-Singla-1-3-0-9 plesae create new issue or look for other issues.
Till then star the repo ⭐
