### ISSUE TITLE
Want to add footer to the contact page

### ISSUE THREAD

**Issue by KAMYAVERMA** [Arun9739/Paryatana#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There are footers in home, about and our page but there is no footer in contact which doesn't go wit the theme, want to add footer in the same.

**Screenshots**
![footer aryun](https://user-images.githubusercontent.com/85511676/194719716-0a01abee-42a4-4216-b3dd-04665a06a9f3.jpg)

**Comment by KAMYAVERMA** [comment]
Will two PR/RM in same repository be counted as 2PRs or 1PR?

**Comment by disha815** [comment]
hey, can you assign this to me

**Comment by Arun9739** [comment]
@KAMYAVERMA and @disha815 There is already a footer in the contact page.
Plz create valid issues or look for other issues.

Show your support by stargzing the repo 🌟
