### ISSUE TITLE
Improve and Refactor the check now card style

### ISSUE THREAD

**Issue by abhishekrd** [Arun9739/Paryatana#165]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- In current project, the card for checking the car rentals and hotel is not well aligned with other cards. 
- also, the input fields are of old style, I would like to give them a modern css feel.
**Screenshots**
![Screenshot 2022-10-09 014637](https://user-images.githubusercontent.com/88556842/194726464-7ec74793-b4d5-495c-9c7a-7f005f699ec3.png)

@Arun9739 please assign me this issue

**Comment by abhishekrd** [comment]
@Arun9739 can you please assign me this issue

**Comment by Arun9739** [comment]
Go ahead @abhishekrd 
Show your love by stargazing the repo 🌟
