### ISSUE TITLE
Improving buttons and applying hovering effects

### ISSUE THREAD

**Issue by anirudhsalaria** [Arun9739/Paryatana#170]
### Work to be done

1. Wanted to improve the buttons in the website by applying box shadow and enlarge on hovering effect.
2. Wanted to apply enlarge on hovering effect on "Places you must visit" and "Popular places" section.
3. Wanted to improve the "home","about","our tours","contacts" Links provided in the footer section by applying different effects.

Kindly Assign me this task :)

> These changes will make the website more beautiful 💯  :)

**Comment by Arun9739** [comment]
@anirudhsalaria Go ahead
Show your love by stargazing the repo 🌟
