### ISSUE TITLE
Change design of testimonial section in about page.

### ISSUE THREAD

**Issue by Adi-ty** [Arun9739/Paryatana#172]
I can design testimonial section separately in a carousel like manner 
![Screenshot 999](https://user-images.githubusercontent.com/92062352/194747460-15c0d6a1-7a67-4f0e-a6d2-0156d63ea382.png)
which will give a better look to the website.

**Comment by spiderxp3** [comment]
Can I work on this? Assign me

**Comment by Arun9739** [comment]
Go ahead @Adi-ty 
If you design new testimonial then remove the old one

SHow your support by stargazing the repo 🌟

**Comment by Arun9739** [comment]
@spiderxp3 Thank you for your interest 
Plz look for other issues or create new issues

Star the repo ⭐ to showcase your love.

**Comment by Arun9739** [comment]
@Adi-ty Plz finish your task early

**Comment by Arun9739** [comment]
@Adi-ty This issue will be unassigned to you due to inactivity
Anyone can take up this issue.

**Comment by itzwow** [comment]
Hey @Arun9739  I would like to work on this issue. Can you kindly assign me this issue

**Comment by Arun9739** [comment]
@itzwow Go ahead
Star the repo 🌟 to show your support

**Comment by Arun9739** [comment]
@itzwow Plz finish your task early
