### ISSUE TITLE
update content of about page.

### ISSUE THREAD

**Issue by spiderxp3** [Arun9739/Paryatana#173]
* In about section, content is same and irrelevant with project.

**Comment by spiderxp3** [comment]
can I work on this.

**Comment by Arun9739** [comment]
Go ahead @spiderxp3 
Show your support by stargazing th repo 🌟

**Comment by Arun9739** [comment]
Go ahead @spiderxp3 
Show your support by stargazing th repo 🌟

**Comment by Arun9739** [comment]
Go ahead @spiderxp3 
Show your support by stargazing th repo 🌟

**Comment by AnishKumarGarg** [comment]
can i solve this?

**Comment by Arun9739** [comment]
@spiderxp3 plz finish your task early

**Comment by Arun9739** [comment]
@AnishKumarGarg Plz look for other issues or create new issues.
Star the repo 🌟 to show your support.

**Comment by spiderxp3** [comment]
Okk I will finish it by tomorrow.
