### ISSUE TITLE
updating the contact section and the cost

### ISSUE THREAD

**Issue by jaisinha** [Arun9739/Paryatana#178]
1)The info in the contact section is gibberish so I will update it
2)Will add commas in the cost

**Comment by Arun9739** [comment]
Go ahead @jaisinha 
Show your support by stargazing the repo 🌟

**Comment by Arun9739** [comment]
@jaisinha plz finish your task early

**Comment by Arun9739** [comment]
@jaisinha Due to inactivity this issue will be closed.
