### ISSUE TITLE
Making navbar hoverable

### ISSUE THREAD

**Issue by MridulTi** [Arun9739/Paryatana#18]
## Is your feature request related to the problem? Please describe.
As of right now, the navbar is static as in when the user scrolls down the navbar gets scroll up hence to get to the scroll bar the user has to go to the top
### A clear and concise description of what you want to happen.
I would like to make the navbar to be fixed at the top of the screen so that even if the user scrolls the navbar stays on the top of the screen and thus become easily accessible

something like this 
![image](https://user-images.githubusercontent.com/92802892/193564047-ddd578b8-5826-40c0-a008-59fbac606c55.png)
![image](https://user-images.githubusercontent.com/92802892/193564084-eefb7c9d-fd98-41bb-8240-04a058e25fe9.png)
Thus assign me this issue

**Comment by kanishk6103** [comment]
I can fix it

**Comment by Arun9739** [comment]
@MridulTi Go ahead
Please show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@kanishk6103 Please look for other issue or create new issue.
Please show your love by starring the repo 🤩

**Comment by kanishk6103** [comment]
> @kanishk6103 Please look for other issue or create new issue. Please show your love by starring the repo 🤩

Sir, i have already solved this issue you just have to review the PR. Can you kindly please check it?

**Comment by MridulTi** [comment]
please , do let me know where this issue goes, then only I will make the PR

> @MridulTi Go ahead Please show your love by starring the repo 🌟

**Comment by MridulTi** [comment]
@Arun9739 This is to inform you that I have made the desired changes kindly review it
