### ISSUE TITLE
Favourites page is not visible

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#183]
*What is the bug**
- There is one page named Favourites., which is after contact page. That is not visible now, due to some problem.

**Expected behavior**
- Favourites.html should appear in navbar.
- Favourites.html is already created, you just need to add the link in navbar.

**Comment by Tusharjain123** [comment]
Hey @Arun9739 Can I work on this issue?

**Comment by musavveer** [comment]
Hey @Arun9739 I would like to work on this issue. Please do assign this issue to me.

**Comment by Arun9739** [comment]
@Tusharjain123 Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@AnishKumarGarg and @musavveer Thank you for your interest
Plz create new issues or look for other issues present

Leave a star 🌟 to show your love.
