### ISSUE TITLE
Improving the UI of the CONTACT US form

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#184]
**Is your feature request related to a problem? Please describe.**
- The contact us form in the Contact page beside the map has very old format. Need to enhance it. 

**Describe the solution you'd like**
- You need to make sure that it should align with the map.
- You need to add feature to textfields, buttons etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/84305637/194893257-e3dde8f3-06a7-4405-8773-dba3d518aaa9.png)

**Comment by Arun9739** [comment]
@Coderner Go ahead
Star the repo 🌟 to show your support

**Comment by Arun9739** [comment]
@shardendu930 Thank you for your interest.
Plz create a new issue or look for other issue.
Show your support by stargazing the repo 🌟

**Comment by muskaan04** [comment]
i would like to work on this?

**Comment by Arun9739** [comment]
@muskaan04 Plz look for other issues or create new issues
Thank you for your interest
Star the repo 🌟 to show your support
