### ISSUE TITLE
Social media links opening in same tab

### ISSUE THREAD

**Issue by AvadhootK** [Arun9739/Paryatana#185]
*What is the bug**

The social media links in the footer are opening in the same tab. The user has to press "back" button in order to come to the website again.

**Expected behavior**

The social media links should open in new tabs for good user experience. 

**Additional context**

Hey @Arun9739 ,
Can I work on this issue?

**Comment by Arun9739** [comment]
@AvadhootK Go ahead
Show your love by stargazing the repo 🌟

**Comment by AvadhootK** [comment]
Thanks, Starred the repo!
