### ISSUE TITLE
Shadow effect of "OUR TOURS" button in navbar not working like other buttons

### ISSUE THREAD

**Issue by Coderner** [Arun9739/Paryatana#187]
![Screenshot (8)](https://user-images.githubusercontent.com/85217344/194901955-e53795f2-248d-49f1-b11d-aa07ef09a3aa.png)
![Screenshot (9)](https://user-images.githubusercontent.com/85217344/194901961-2edb45b1-b223-4026-9c20-34c930d2e678.png)
![Screenshot (10)](https://user-images.githubusercontent.com/85217344/194901967-43f65edf-8d76-48b5-a078-59d26ee98aa5.png)
![Screenshot (11)](https://user-images.githubusercontent.com/85217344/194901971-99d32389-bf36-4f5a-9762-d69829e4314a.png)
*What is the bug**

**Expected behavior**
Similar elements should be styled uniformly.

**Screenshots**

**Additional context**
@Arun9739 Can I fix the same?

**Comment by Arun9739** [comment]
Good to go @Coderner 
Star the repo ⭐ to showcase your support.
