### ISSUE TITLE
Add Mobile Menu Icon Animation

### ISSUE THREAD

**Issue by febriadj** [Arun9739/Paryatana#188]
### Related Issue
As a web user/visitor, I need a different menu icon when navigation is opened or closed. Therefore, I would like to add the "mobile-menu-icon animation" feature, can I work on this?

### Screenshot (GIF)
![feature](https://user-images.githubusercontent.com/73212374/194900560-f3c94bb7-bacc-41e0-804b-6e4269fc3907.gif)

**Comment by Arun9739** [comment]
Go for it @febriadj 
Show your love by stargazing the repo 🌟
