### ISSUE TITLE
Giving Slideshow Effect to the Image Slider in the About page 

### ISSUE THREAD

**Issue by pandeatul27** [Arun9739/Paryatana#19]
**Is your feature request related to a problem? Please describe.**
The slides in the image slider of the about page don't change automatically, nor it has a next or previous button.
**Describe the solution you'd like**
I can give a slide show effect to it so that the slides can change automatically.
**Screenshots**

**Comment by pandeatul27** [comment]
@Arun9739  Can I work on this issue under hactoberfest??

**Comment by Arun9739** [comment]
Go ahead @pandeatul27 
Please show your love by starring the repo 🌟
