### ISSUE TITLE
Transition effect for Destination in home page

### ISSUE THREAD

**Issue by ANSHUMANDAS1506** [Arun9739/Paryatana#193]
A basic transition effect needed in the destination card in homepage

**Comment by ANSHUMANDAS1506** [comment]
I would like to do this part in your website, Can you please assign it to me?

**Comment by Arun9739** [comment]
Go ahead @ANSHUMANDAS1506 
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@ANSHUMANDAS1506 If you want to work on this issue again 2 days time will be given
