### ISSUE TITLE
Color of social media icons on hovering

### ISSUE THREAD

**Issue by AvadhootK** [Arun9739/Paryatana#194]
The color of social media icons in the footer, on hovering, should match their own theme color.
Eg : red for instagram, blue for facebook etc.
Can I work on this issue?

**Screenshots**

![Screenshot (676)](https://user-images.githubusercontent.com/72447002/194992158-a22273b6-1e20-4545-a066-2367a968cc14.png)

**Comment by Arun9739** [comment]
Good catch @AvadhootK 
Go ahead 💯 
Star the repo 🌟 to shw your support.
