### ISSUE TITLE
Adding style to navbar

### ISSUE THREAD

**Issue by priyanshu070702** [Arun9739/Paryatana#196]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Screenshots**

![09 10 2022_21 17 30_REC](https://user-images.githubusercontent.com/79093860/195010666-c651806f-f22f-447c-8298-8f055c83012d.png)
![09 10 2022_21 17 48_REC](https://user-images.githubusercontent.com/79093860/195010674-03da22f2-e559-44ca-beeb-d3b944507bee.png)
![09 10 2022_21 18 02_REC](https://user-images.githubusercontent.com/79093860/195010696-e2bb4fcd-c7b8-4a7b-8d73-23273ece28a8.png)

**Comment by Arun9739** [comment]
@priyanshu070702 Go ahead
Show your support by stargazing the repo 🌟

**Comment by Arun9739** [comment]
@priyanshu070702 If you want to work again on this issue, 2 days will be given.
Plz finish the task.

**Comment by Arun9739** [comment]
@priyanshu070702 Due to inactivity this issue will be closed.
