### ISSUE TITLE
Adding Profile for the User

### ISSUE THREAD

**Issue by Hegde2002** [Arun9739/Paryatana#199]
i want to add a profile section for the user which will be containing his name , PhoneNo, bookmarked places and  his travel history.
if we click on the favourites button(heart icon) it will just redirect to the home page ,If it remains user experience will be not good as he whenever he want to add  any places to bookmarks it will take him to home page.whether i have to make any changes there?

**Comment by Arun9739** [comment]
Go ahead @Hegde2002 
Nice thought 💯 
Design the profile as per your choice, no problem at all.

**Comment by Arun9739** [comment]
@Arun9739 If you want to work on this issue, 2 days time will be given.
Plz finish your task early.

**Comment by Arun9739** [comment]
@Hegde2002 Due to inactivit this issue will be closed
