### ISSUE TITLE
Adding links to the social media buttons under Contact page

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#2]
**Is your feature request related to a problem? Please describe.**
Need to add links to the social media buttons present under contact section.

**Describe the solution you'd like**
- You need to add just links to respective social media handles.
- For eg.  after clickinh the twitter button it should go to twitter.
- You should not harm the project's structure.
- There are total five social mediabuttons to be updated.

The section :
![image](https://user-images.githubusercontent.com/84305637/193471675-9e70ecd7-5d10-42ad-931a-2d113f4b6215.png)

**Additional context**

**Comment by tokyo3001** [comment]
@Arun9739 Can you assign me this issue?

**Comment by Arun9739** [comment]
@tokyo3001 go ahead !!
Please showcase your love by starring the repo :)

**Comment by itzwow** [comment]
If the issue still pending I would love to work on  the issue. 
Can you kindly assign me @Arun9739

**Comment by Arun9739** [comment]
@tokyo3001 Plz finish the work early, else issue will be assigned to other.

**Comment by Arun9739** [comment]
@itzwow Plz look for other issues or create new issues.
Show your support by stargazing the repo 🌟

**Comment by tokyo3001** [comment]
@Arun9739 PR #17 has already been merged for this issue 6 days ago.

**Comment by Arun9739** [comment]
@tokyo3001 Ok
