### ISSUE TITLE
Visibility of "Travel" button on Home page

### ISSUE THREAD

**Issue by sidd6p** [Arun9739/Paryatana#200]
![image](https://user-images.githubusercontent.com/91800813/195129973-b63e2c17-2529-4529-bc09-57cf88b1de87.png)

While hovering over the travel button it color changes into less visible colour, from UX/UI point of view it must get more visible and catchy to end-user eye.

__Would like to improve it.__

**Comment by Arun9739** [comment]
@sidd6p Go ahead
Star the repo 🌟 to showacse your support.

**Comment by Arun9739** [comment]
@myth-mithra Plz look for other issues or craete new issues
Star the repo 🌟 to showcase your support
