### ISSUE TITLE
The carousel on "Contact" page doesn't work

### ISSUE THREAD

**Issue by AvadhootK** [Arun9739/Paryatana#208]
*What is the bug**

The carousel on "Contact" page does not have other images like other pages.

**Expected behavior**

Add more images to the "Contact" page carousel like all other pages.

**Screenshots**

![Screenshot (683)](https://user-images.githubusercontent.com/72447002/195162252-142dcf92-b0f6-45ce-920d-66494e04ddc9.png)

**Comment by Arun9739** [comment]
@AvadhootK Go ahead
Show your support by stargazing the repo ⭐

**Comment by IsuruAkalanka** [comment]
Hi, @AvadhootK are you working on this or shall I work on this issue

**Comment by AvadhootK** [comment]
Hey @IsuruAkalanka , I am almost done with the issue :)

**Comment by IsuruAkalanka** [comment]
It is fine.

**Comment by Arun9739** [comment]
@AvadhootK Plz finish your task early.

**Comment by Arun9739** [comment]
@AvadhootK Due to inactivity this issue is closed.
