### ISSUE TITLE
Hotel/Car Rental card has uneven margin

### ISSUE THREAD

**Issue by RajatSatashiya** [Arun9739/Paryatana#209]
*What is the bug**
The hotel / car rental card has uneven margin (or padding). This is causing the text to be not centered and thus causing unusual background color issue (the yellow bg color at the bottom of the card)

**Expected behavior**
Will fix the margin (or padding) or whatever the issue is. The bg color will look proper, the textual part will be centered. Will also make the transition more smoother.

**Screenshots**
![image](https://user-images.githubusercontent.com/74141334/195175179-7a9b388b-a565-4874-9a36-aa93c25eb73c.png)

**Comment by Arun9739** [comment]
@RajatSatashiya Go ahead
Show your support by stargazing the reop 🌟
