### ISSUE TITLE
The yellow portion of the form is not in correct position and size

### ISSUE THREAD

**Issue by HarshDDalwadi** [Arun9739/Paryatana#211]
*What is the bug**
The yellow portion is not in match with the User Interface

**Expected behavior**

**Screenshots**
![Screenshot (661)](https://user-images.githubusercontent.com/102744867/195177039-2c795267-db05-42f2-b3e8-961cae24f85a.png)

**Additional context**

**Comment by Arun9739** [comment]
@HarshDDalwadi Thank you for this interest
But this issue is already present and has been assigned to someone else.
Plz look for other issues or create new issue.

Star the repo 🌟 to show your support.
