### ISSUE TITLE
Modified/Fixed the footer transition at scale of 1.5

### ISSUE THREAD

**Issue by Prajwalgupta** [Arun9739/Paryatana#213]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
-Added the transition in the footer buttons. This change improve the visuals of the site by adding the transition in buttons in the footer. From UX/UI point of view it looks good.

**Screenshots**
![Paryatana - Google Chrome 11-10-2022 00_59_48](https://user-images.githubusercontent.com/92562327/195209905-beed1d36-2cda-48f0-a0a1-55756de9ce73.png)

**Comment by Prajwalgupta** [comment]
You can see the transition made by me in video below.

https://user-images.githubusercontent.com/92562327/195326237-92fb5a16-8644-414e-97d8-bf03e048dfee.mp4

**Comment by Arun9739** [comment]
Nice !!
Go ahead @Prajwalgupta 

Show your support by stargazing the repo 🌟
