### ISSUE TITLE
Want to Add More option of hotels and car model in the form 

### ISSUE THREAD

**Issue by Dharansh-Neema** [Arun9739/Paryatana#218]
**### I would like to add more option while making selection for hotel and car model. **
**Screenshots**
Before:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/89770584/195388829-a1fa9fed-79e4-419f-90d6-640e44623cb2.png">
<img width="265" alt="image" src="https://user-images.githubusercontent.com/89770584/195388911-bfad4b50-8e97-436f-b3c9-e8c6df2f01d6.png">
After:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/89770584/195389177-fc3bc77b-3a0b-4dfb-8fe6-77c96f6064f2.png">

**Comment by Dharansh-Neema** [comment]
Can you please assign it to me @Arun9739

**Comment by Arun9739** [comment]
@Dharansh-Neema Go ahead
Star the repo 🌟 to show your support

**Comment by Dharansh-Neema** [comment]
Created a Pull Request for this issue 
Pull Request Number: #221
