### ISSUE TITLE
Improving the CONTACT US page form 

### ISSUE THREAD

**Issue by Dharansh-Neema** [Arun9739/Paryatana#223]
**I want to make contact us form working i.e. after submitting the form we will get a mail of the user.**
Additional Features:
Make name and email input type as required.
------------------------------------------------------------------------------------------------------------------------       
@Arun9739 please assign this to me

**Comment by Arun9739** [comment]
@Dharansh-Neema Go ahead
Star the repo ⭐ to show your support

**Comment by Dharansh-Neema** [comment]
Pull request is submitted #270
