### ISSUE TITLE
UI allignment in filter selections div

### ISSUE THREAD

**Issue by shubhamjain1922** [Arun9739/Paryatana#225]
In our tours page, filter selection div does not have correct allignment. Its more right alligned and not center.

![image](https://user-images.githubusercontent.com/54628090/195457025-d229d253-cca7-47a4-82ce-4c68e93da96b.png)

Please assign the issue to me.

**Comment by Arun9739** [comment]
@shubhamjain1922 thank you for your interest
But this issue is already present and someone is in the way to reslove it.

Please look for other issue or create new issue.

Star the repo 🌟 to show your love.
