### ISSUE TITLE
Navbar not responsive

### ISSUE THREAD

**Issue by shubhamjain1922** [Arun9739/Paryatana#226]
In tablet mode, navbar is not despalying as it should, links are overlapping with logo.

![image](https://user-images.githubusercontent.com/54628090/195457383-14ae26d3-cece-4e54-b6f6-4990ef30445e.png)

PLease assign the issue to me.

**Comment by Arun9739** [comment]
@shubhamjain1922 Thank you for your interest
But this issue is already present and has been assigned to someone else.
Plz look for other issue or create new issue.

Star the repo 🌟 to show your support.
