### ISSUE TITLE
need better hover for footer pages nav

### ISSUE THREAD

**Issue by Devrajsinh03** [Arun9739/Paryatana#229]
**Is your feature request related to a problem? Please describe.**
the footer nav for pages is not giving good look for hover
**Describe the solution you'd like**
a bit better UI for footer pages nav
**Screenshots**
<img width="1440" alt="Screenshot 2022-10-13 at 10 05 36 AM" src="https://user-images.githubusercontent.com/103804567/195503159-e39cf7dc-c8c0-4c08-b04f-5e60d73fc2a9.png">

**Comment by Arun9739** [comment]
Go ahead @Devrajsinh03 
Star the repo 🌟 to show your support.
