### ISSUE TITLE
Sending email by clicking SUBMIT NOW button on contact.html

### ISSUE THREAD

**Issue by BiswajitSahoo-tech** [Arun9739/Paryatana#23]
**Is your feature request related to a problem? Please describe.**

Till now submit button on the contact page does not do anything, like it should send the message to somewhere e,g- mail inbox, right

**Describe the solution you'd like**

My solution is to upon clicking the SUBMIT NOW button an email should be sent to the concerned authority. And this email message has all the information input to the user on the contact form

**Screenshots**
![image](https://user-images.githubusercontent.com/73599660/193572738-8f9c7753-23db-4994-884d-1a96ab22007f.png)

**Comment by BiswajitSahoo-tech** [comment]
Please assign this to me @Arun9739 
Thanks

**Comment by Arun9739** [comment]
Go ahead @BiswajitSahoo-tech 
Star the repo 🌟 to showacse your love
