### ISSUE TITLE
Just a bit typo in the documentation.

### ISSUE THREAD

**Issue by wickedwisdom0911** [Arun9739/Paryatana#233]
*What is the bug**
In the readme under the Paryatana title "the travel agency are also dispalyed" the spelling of displayed is incorrect.

"**Expected behavior**
Dispalyed to be corrected to displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/78411069/195560979-42e80eba-b1f4-4efc-8f23-f5c2291403a3.png)

**Additional context**

**Comment by wickedwisdom0911** [comment]
Though a small issue , would be a great issue for me , as its my first time in Hacktoberfest

**Comment by Arun9739** [comment]
@wickedwisdom0911 Good catch
Changing a small letter can't be considered as "open source contribution"
But I appreciate your enthusiasm

Plz look for other issues or create new issues.

Star the repo 🌟 to show your support.
