### ISSUE TITLE
Fix favourites.html page footer

### ISSUE THREAD

**Issue by charandeep7** [Arun9739/Paryatana#237]
*What is the bug**
favourites.html doesn't look good like other pages

**Expected behavior**
NA

**Screenshots**
![Footer](https://user-images.githubusercontent.com/96859500/195621647-514269cd-2f9b-4036-9f67-dc50c5433c4e.jpg)

**Additional context**
Please assign this bug to me. I'll fix this bug asap.

**Comment by Arun9739** [comment]
@charandeep7 Go ahead
Show your support by stargazing the repo 🌟
