### ISSUE TITLE
Improving ui of the card

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Arun9739/Paryatana#24]
The ui of the card can be improved 
I can improve by giving them a tilt effect and also giving some hover effects making the card little interactive 
![Screenshot_20221003_173706](https://user-images.githubusercontent.com/96341386/193572943-4ec41a7e-825c-4d7e-b609-9647f3e491e2.jpg)

**Screenshots**

**Comment by Arun9739** [comment]
Go ahead @vaibhavsharma1234 
Show your love by starring the repo 🤩

**Comment by Arun9739** [comment]
@vaibhavsharma1234 plz finish your task early

**Comment by vaibhavsharma1234** [comment]
Sorry will do
I got Ill that's why couldn't do it
Will do it asap

**Comment by vaibhavsharma1234** [comment]
sorry i will not be able to do this 
honestly i am currently not able to get interested to do this open source feels like i am forcing so thats why opting out
