### ISSUE TITLE
No proper  description in the About Us section of your Website

### ISSUE THREAD

**Issue by SaiSantosh2209** [Arun9739/Paryatana#244]
* I want to replace the lorem ipsum text present in the About us section with some proper Text for enhancing the user experience.
* I would just give a brief description about your travel website
![Screenshot (8)](https://user-images.githubusercontent.com/83724995/195669615-6762bf4b-d01d-4794-950e-696cfd704d56.png)

**Comment by Arun9739** [comment]
@SaiSantosh2209 Go ahead
There are total 4 cards, plz change all lorem content to proper content.
You can change the heading also, as per your convenience.

Star the repo 🌟 to show your support.
