### ISSUE TITLE
Improvement in Home page.

### ISSUE THREAD

**Issue by beauty108** [Arun9739/Paryatana#245]
*What is the bug**
Size of the form card in home page is not adjustable with the surrounding.

**Expected behavior**
The size of the form card i.e., circled with red must be equal to the size of cards circled with green in the given screenshot. 

**Screenshots**
![Screenshot 2022-10-13 231627](https://user-images.githubusercontent.com/111839696/195670181-0b923a15-6315-4e9c-985d-5899c64c2f6c.png)

**Comment by beauty108** [comment]
Can I work on this ?
Please assign this task to me, I want to improve others bugs also in this page.

**Comment by Arun9739** [comment]
@beauty108 Go ahead
Star the repo 🌟 to show your support

**Comment by Arun9739** [comment]
@beauty108 If the cards are not visible due to some problem, plz copy it from the tours page.

**Comment by beauty108** [comment]
Okay I will fix it soon. Thankyou : )

**Comment by beauty108** [comment]
@Arun9739 Done :-)
