### ISSUE TITLE
Providing proper social media handle links  in About us section

### ISSUE THREAD

**Issue by SaiSantosh2209** [Arun9739/Paryatana#246]
* I would like to  provide proper social media links which are present in the about us section of your website.
* I will just provide the links of your social media handles of your
![Screenshot (9)](https://user-images.githubusercontent.com/83724995/195671063-43e066ee-ca76-4412-a89d-c04bcd2bba9b.png)
 account

**Comment by Arun9739** [comment]
@SaiSantosh2209 Go ahead
Just add the inks of the social media itself like https://twitter.com.
No need to add it for particular account.

Star the repo 🌟 to show your support.

**Comment by SaiSantosh2209** [comment]
@Arun9739 Please review my PR
