### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by arzitmahajan** [Arun9739/Paryatana#249]
**Is your feature request related to a problem? Please describe.**
The date and other cards on carousal are not in proportion so aligning it.

**Describe the solution you'd like**
Adding parallax image in background in place of carousal and then applying gradient on carousal and aligning the cards on carousal

**Screenshots**

**Comment by Arun9739** [comment]
@arzitmahajan Go ahead
Star the repo 🌟 to show your support.
