### ISSUE TITLE
Adding links to the social media icons

### ISSUE THREAD

**Issue by NateNear** [Arun9739/Paryatana#25]
Please allow me to add links to the social media icons present in the "About" section and the "Who we are" section.
![issue3](https://user-images.githubusercontent.com/92938055/193573228-b26899b0-70ab-4603-8dcf-0f5d984b1662.PNG)

**Comment by Rituraj-13** [comment]
Hey @Arun9739 I want to work on this, can you please assign me for this?

**Comment by Arun9739** [comment]
@Rituraj-13 Thank you for your interest.
But this issue is alreday present and assigned to someone else.
Please create new issue or look for other issue.

Please show your love by starring the repo
