### ISSUE TITLE
Make textarea in contact.html responsive

### ISSUE THREAD

**Issue by Harshit-2112** [Arun9739/Paryatana#253]
I have inspect contact page. query box is not adjusting in a right way on smaller screen. 
Please Assign me this issue to work upon.
make query box responsive.
Thank you

**Comment by Arun9739** [comment]
@Harshit-2112 Go ahead
Star the repo 🌟 to show your love.

**Comment by Arun9739** [comment]
@Harshit-2112 Do you want to work again on this issue? Plz finish the task early
