### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by samipashaa** [Arun9739/Paryatana#254]
**Is your feature request related to a problem? Please describe.**

I noticed this repository doesn't have a license.

If you don't mind I would like to add one to clarify what others can and can't do with this repository.

**Describe the solution you'd like**

I was thinking either the apache or the MIT license would work.

**Comment by Arun9739** [comment]
@samipashaa Go ahead
Add MIT license.

Show your support by stargazing the repo 🌟

**Comment by samipashaa** [comment]
Sure, on it!

**Comment by samipashaa** [comment]
I have added MIT license can you please check and give feedback please.
