### ISSUE TITLE
improve the header section

### ISSUE THREAD

**Issue by creater-shikha** [Arun9739/Paryatana#257]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

improve the header section and initial images in the home page
**Screenshots**
![Paryatana - Google Chrome 10_9_2022 5_11_26 PM](https://user-images.githubusercontent.com/69755719/195850440-bc515f2b-8f78-4199-8945-1fe0b5e4a24a.png)
I already make the changes plz merge if u like the changes

**Comment by creater-shikha** [comment]
assign this issue  to me

**Comment by Arun9739** [comment]
@creater-shikha Nice
Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@creater-shikha Plz finish the task early

**Comment by Arun9739** [comment]
@creater-shikha Due to inactivity this issue will br closed
