### ISSUE TITLE
Unexpected behaviour in cards of about page

### ISSUE THREAD

**Issue by Shurtu-gal** [Arun9739/Paryatana#258]
**What is the bug**
Cards are stretching reducing the readability of text content.

**Expected behavior**
The card should float up instead of stretching up.

**Screenshots**
![image](https://user-images.githubusercontent.com/100484401/195864561-f5889a23-2240-421c-b04e-eaea5c280453.png)

**Comment by Shurtu-gal** [comment]
Can I get assigned to this issue?

**Comment by Arun9739** [comment]
@Shurtu-gal Go ahead
Star the repo 🌟 to show your support.
