### ISSUE TITLE
Need more margin between "popular packages" cards to maintain enough space while hovering over them

### ISSUE THREAD

**Issue by sidd6p** [Arun9739/Paryatana#259]
While hovering to "popular packages" cards on home page, then they looks like overlapping

While hovering it should not look like hovering and user can still get the focus on the card to which he/she is looking

![image](https://user-images.githubusercontent.com/91800813/195866179-c0f3b7e7-8eda-450a-9f73-a2a57df532d2.png)

**Comment by manika137** [comment]
I could take it up.
I would also like to correct the box size for this section on 'Our Tours' page 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/80244229/195964464-f5ccdc2c-723f-488f-b09a-0a4acbd6db31.png">

**Comment by darshikaguptaa** [comment]
Hey @Arun9739 I would like to work on this. Please assign this issue to me

**Comment by Arun9739** [comment]
@sidd6p Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@manika137 Plz create new issue for that, I will assign you.
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@darshikaguptaa Thank you for your interest
Plz create new issues or look for other issues.
Star the repo 🌟 to show your love.
