### ISSUE TITLE
Send query or message as email, instead of doing nothing

### ISSUE THREAD

**Issue by sidd6p** [Arun9739/Paryatana#260]
- On contact, there should be some minimum action after user submit query or feedback

- Solution can be opening the user email. Already populated email with body containing the message or query from the user. In this way we even do not need to ask user for the email.

![image](https://user-images.githubusercontent.com/91800813/195869135-3b119cbf-6758-4529-94f6-252775ca09e4.png)

_email used is dummy_

**Comment by Shurtu-gal** [comment]
**Interested**

**Comment by Arun9739** [comment]
@sidd6p and @Shurtu-gal Thanks for this issue.
But the issue is alreday submitted by someone else and has been resolved.

Plz create new issues or look for other issues.
Star the reop 🌟 to show your support.
