### ISSUE TITLE
Footer responsiveness 

### ISSUE THREAD

**Issue by darshikaguptaa** [Arun9739/Paryatana#271]
Footer is not responsive in mobile view

![Screenshot_2022-10-15-18-06-53-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/76615910/195986819-145aff17-f301-4724-a984-aa1ae1a40e12.jpg)

**Comment by darshikaguptaa** [comment]
Hey @Arun9739 I'd like to fix this

**Comment by Arun9739** [comment]
@darshikaguptaa Go ahead
Star the repo 🌟 to show your support.

**Comment by darshikaguptaa** [comment]
Hey @Arun9739 I've fixed the issue in PR #288 Please take a look at it
