### ISSUE TITLE
Adding actual content in ABOUT us Section 

### ISSUE THREAD

**Issue by Dharansh-Neema** [Arun9739/Paryatana#274]
**Replacing the random text in ABOUT Section with some actual content that make sense.** 

**Screenshots**
<img width="752" alt="image" src="https://user-images.githubusercontent.com/89770584/195992644-bc122a3f-7ccd-422e-bf64-2a10e0cc98b8.png">

**Comment by Arun9739** [comment]
@Dharansh-Neema Thannk you for your interest
But there is already actual content is there.
The site has been updated.

Plz create new issues or look for other issues.
Star the repo 🌟 to show your love.
