### ISSUE TITLE
Want to fix the testimonial card in about us page.

### ISSUE THREAD

**Issue by CHIRANTAN-001** [Arun9739/Paryatana#277]
*What is the bug**
On the about us page, the testimonial card section has height and content adjustment issues, want to fix this issue.

**Expected behavior**
Content should be well-adjusted inside the yellow color testimonial card.

**Screenshots**
![image](https://user-images.githubusercontent.com/82677314/196021082-fe0daa57-8756-44aa-81d2-87223433a6a8.png)

**Additional context**
In addition, to fix this problem, I want to add a back-shadow to this card.

**Comment by Arun9739** [comment]
@CHIRANTAN-001 Go ahead
Star the repo 🌟 to show your support.
