### ISSUE TITLE
The navbar is fixed, to help user access it even after scrolling, it needs to be static on the viewport

### ISSUE THREAD

**Issue by kanishk6103** [Arun9739/Paryatana#28]
*What is the bug**
The navbar is fixed and disappears as the user scrolls beyond the viewport and needs to be fixed.

**Expected behavior**
The navbar should move along as the user scrolls

**Screenshots**
![image](https://user-images.githubusercontent.com/72643990/193579761-99d666ad-8d33-4b8b-a573-3a9948e43b89.png)

**Additional context**

**Comment by kanishk6103** [comment]
can you assign this issue to me now with the label? @Arun9739

**Comment by Arun9739** [comment]
@kanishk6103 Thank for creating an issue.
But there are already issues present on the navbar.
Please create new issue or look for others.

Star the repo 🌟 to showcase your love.
