### ISSUE TITLE
Adding More Popular packages and places you must Visit

### ISSUE THREAD

**Issue by Dharansh-Neema** [Arun9739/Paryatana#284]
Adding More different type of popular packages.

**Screenshots**
Before:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/89770584/196040054-04f0447e-4fac-4537-8e7c-383e69e3c553.png">
After:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/89770584/196040074-3ff6cd32-9446-4f33-b6eb-76c178c72cac.png">
**The new Image is only for displaying purposes!!**

**Comment by Arun9739** [comment]
@Dharansh-Neema Go ahead
Add atleast 2 different packages.

Star the repo 🌟 to show your support.
