### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by kushaljgec2025** [Arun9739/Paryatana#287]
**Is your feature request related to a problem? Please describe.**
"Check Now" Hover is not looking good.

**Describe the solution you'd like**
I can add good hover effect and genuine colour combination
**Screenshots**
![image](https://user-images.githubusercontent.com/108950724/196225188-63013d12-a570-4917-9bb0-82f4356a19fe.png)

**Comment by kushaljgec2025** [comment]
please Assign me the task

**Comment by Arun9739** [comment]
@kushaljgec2025 Go ahead
Star the repo 🌟 to show your love.

**Comment by kushaljgec2025** [comment]
I have already commit a pull request. please check it out.
