### ISSUE TITLE
Want to add a newsletter in the footer section

### ISSUE THREAD

**Issue by sayan404** [Arun9739/Paryatana#289]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Screenshots**
What I am planning to do . Always Welcome to your suggestions ...

![Screenshot 2022-10-17 213714](https://user-images.githubusercontent.com/95490367/196228144-9c446f7c-5115-466e-9f3f-e3fd0d80d2ee.png)

**Comment by sayan404** [comment]
I want to work in this issue . Pls assign me this issue @Arun9739

**Comment by Priyanshu-su30** [comment]
Plz assign me this issue

**Comment by Arun9739** [comment]
@sayan404 Go ahead
Star the repo 🌟 to show your love.

**Comment by Arun9739** [comment]
@Priyanshu-su30 Thank you for your interesr=t
But plz look for other issues or create new issues

Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@Priyanshu-su30 Thank you for your interesr=t
But plz look for other issues or create new issues

Star the repo 🌟 to show your support.
