### ISSUE TITLE
No proper description in the Contact us section.

### ISSUE THREAD

**Issue by SaiSantosh2209** [Arun9739/Paryatana#291]
* I would like to add some proper text in the contact us section  in the place of the lorem ipsum 
![Screenshot (14)](https://user-images.githubusercontent.com/83724995/196235754-d70cb296-88ae-416e-9c37-f75e66549e77.png)

**Comment by acenasir** [comment]
@SaiSantosh2209 Please assign this to me and add the hactktoberfest labels

**Comment by Arun9739** [comment]
@SaiSantosh2209 Go ahead
Star the repo 🌟 to show your love

**Comment by Arun9739** [comment]
@acenasir Thank you for our interest
Plz create new issues or look for other issues.

Star the repo 🌟 to show your support.

**Comment by SaiSantosh2209** [comment]
Hey @Arun9739 please merge my PR

**Comment by SaiSantosh2209** [comment]
@Arun9739  please review my PR
