### ISSUE TITLE
Adding proper images to Shimla and Kashmir sections

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#3]
**Is your feature request related to a problem? Please describe.**
- Add proper image to Shimla and Kashmir section present in "Home" and "Our toors" pages.

**Describe the solution you'd like**
- Add related images like Kashmir place image to Kashmir section.
- You need to add the image in image folder.
- The image should fit into the space allocated for it.

**Screenshots**
![image](https://user-images.githubusercontent.com/84305637/193536229-5009e68c-ec5a-4b02-b5ce-c1152b62ac23.png)

**Comment by aniket2003** [comment]
@Arun9739 I would like to work on this issue , could you please assign me this.

**Comment by Arun9739** [comment]
Go ahead @aniket2003 !!
Showcase your love by starring the repo

**Comment by Arun9739** [comment]
Go ahead @aniket2003 !!
Showcase your love by starring the repo

**Comment by riddhitech** [comment]
I would like to contribute , please assign

**Comment by Arun9739** [comment]
@riddhitech please look for other issues or create new issues
Show your support by starring the repo 🌟
