### ISSUE TITLE
Favorites not working and a few UI issues, spoiling the user experience.

### ISSUE THREAD

**Issue by Source-404** [Arun9739/Paryatana#301]
**Is your feature request related to a problem? Please describe.**

- On clicking on Favorite, page gets refreshed,
- Footer is too big and occupies a lot of the screen 
- Rounded edges will suit the the theme more 
 

**Describe the solution you'd like**

I will fix all the above stated issues.

**Screenshots**

![image](https://user-images.githubusercontent.com/72282249/196777267-39c7b2b1-e4ba-44dd-995d-5b9273d32b17.png)

![image](https://user-images.githubusercontent.com/72282249/196777431-adf5bc09-7912-4ee0-a861-3dbb1c5ed96a.png)

**Comment by Source-404** [comment]
@Arun9739 Please assign me this issue

**Comment by Arun9739** [comment]
@Source-404 The favourites page is working(It looks like home page, that's why you got confused)
You can work on other issues.

Star the repo 🌟 to show your support.

**Comment by Source-404** [comment]
@Arun9739 please review my PR #309
