### ISSUE TITLE
Hover issue on footer

### ISSUE THREAD

**Issue by Sidkul2000** [Arun9739/Paryatana#302]
What is the bug*
The hover effect on the tabs on footer is bugged. Even if the mouse is not on the text, the tabs are getting hovered.

*Expected behavior*
The hover effect should be enabled only when the mouse is on the text.

Please assign me this task as I am working on it.

*Screenshots*
![Screenshot (688)](https://user-images.githubusercontent.com/63728680/196780031-dfc8a694-0784-4c17-b7eb-7d597091cf48.png)

**Comment by Arun9739** [comment]
@Sidkul2000 Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@Sidkul2000 Plz finish your task early

**Comment by Sidkul2000** [comment]
> @Sidkul2000 Plz finish your task early

I am sorry the bug is not getting fixed. I have been trying since a few days, but its remainig the same. I will try for a few days more, but I think it would be better to assign the task to someone else. Apologies for the delay.

**Comment by Arun9739** [comment]
@Sidkul2000 Its okay, no problem
Plz star the repo 🌟 to show your support.
