### ISSUE TITLE
UI improvement of the team member card 

### ISSUE THREAD

**Issue by AtriSukul1508** [Arun9739/Paryatana#303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to work upon the ui of the team member cards

**Screenshots**

**Comment by Arun9739** [comment]
@AtriSukul1508 Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@AtriSukul1508 Plz finish your task early

**Comment by Arun9739** [comment]
@AtriSukul1508 Due to inactivity this issue will be closed.
