### ISSUE TITLE
Text going out of the box in about page

### ISSUE THREAD

**Issue by Priyanshu-su30** [Arun9739/Paryatana#304]
As seen in the left side of ss the text is out of the yellow container. I would like to fix it please assign me this!!!

![Screenshot (70)](https://user-images.githubusercontent.com/107869522/196959175-0b785fd3-a291-43a5-993e-ccccfbac18e5.png)

**Comment by Arun9739** [comment]
@Priyanshu-su30 Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@Priyanshu-su30 Plz finish your task early

**Comment by Arun9739** [comment]
@Priyanshu-su30 As this issue has been fixed, it wil be closed
Plz look for other issues or create new issues.
