### ISSUE TITLE
Links Functionalities

### ISSUE THREAD

**Issue by Srish-ty** [Arun9739/Paryatana#307]
**Is your feature request related to a problem? Please describe.**

- some of the links were not leading to the respective pages
- few of links were being opened in the same window and tab, which is distracting for users.
- For newsletter, the given input field wasn't email and users can't get to know if their mail-id is submitted.

**Describe the solution you'd like**

- Wrote code to open the links in a new tab
- corrected links and the respective names given on pages
- created input field for mail to sign-in for newsletter
- created a proper feedback to be given to user once their mail-id is submitted for newsletter
**Screenshots**

**Comment by Arun9739** [comment]
@Srish-ty Go ahead
Star the repo 🌟 to show your support.
