### ISSUE TITLE
Make the copyright year update automatically

### ISSUE THREAD

**Issue by Subha-5** [Arun9739/Paryatana#310]
*What is the bug**
This is not a bug at present, but using a static copyright year forces the developer to change the year every new year. If it's not changed, it can hamper the reputation of the website. So, using Javascript can help us to update the year every time. This maintains the copyright year. Since the current year 2022 is going to end soon, I got an idea of this feature to get introduced.

**Expected behavior**
On every reload, javascript will automatically check the current year to display in copyright year.

**Screenshots**
![Screenshot from 2022-10-21 18-49-51](https://user-images.githubusercontent.com/97968307/197206631-fd1dbbdc-5cdc-4088-95e5-9d4b48a0ec82.png)

**Additional context**
This is very useful as the copyright year will be auto updated by simple JavaScript.

**Comment by Subha-5** [comment]
@Arun9739 please assign me this issue for hacktoberfest '22

**Comment by Arun9739** [comment]
@Subha-5 Go ahead
Star the repo 🌟 to show your support.

**Comment by Subha-5** [comment]
@Arun9739 please review the changes in the pr #313  and close this issue.

**Comment by Subha-5** [comment]
@Arun9739 please review the changes in the pr #316   and close this issue.
