### ISSUE TITLE
Fixing 'your go to tarvel partner' section

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#317]
# What is the bug :
- The first section in home page is taking lot of space and needs to be improved.

# Expected behavior :
- Improvemnt of 'your go to travel partner', so as to make it look better and appropriate.

# Screenshots :
![image](https://user-images.githubusercontent.com/84305637/197392534-e248d0cd-17eb-4f99-8ac6-fbe637c5d28f.png)

**Comment by itzwow** [comment]
Kindly assign me I would like to work on it

**Comment by Arun9739** [comment]
@itzwow Go ahead
Star the repo 🌟 to show your support.
