### ISSUE TITLE
Different footers at different pages

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#318]
# What is the bug :
- The footers are different at different pages. For example home page footer has different style and other pages have different style.

# Expected behavior :
- I want a uniform footers all over the website. Make a footer which suits the best to website.

# Screenshots :

**Comment by RXBlade** [comment]
Hey @Arun9739 I'll take care of it

**Comment by Arun9739** [comment]
@RXBlade Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
If anyone wants to work upon this issue, they can do.

**Comment by ihtishamKhan** [comment]
@Arun9739 I am going to work on it please assign it to me

**Comment by Arun9739** [comment]
@ihtishamKhan Go ahead
Star the repo 🌟 to show your support

**Comment by Ultimateutkarsh11** [comment]
This issue still needs to be fixed, can I work on it @Arun9739?

**Comment by Arun9739** [comment]
@Ultimateutkarsh11 The issue has been fixed.
Plz look for other issues or create new issues.

**Comment by Ultimateutkarsh11** [comment]
> @Ultimateutkarsh11 The issue has been fixed.
> Plz look for other issues or create new issues.
> 
> Plz star 🌟 the repo to show your support

Sure!
