### ISSUE TITLE
Paryatana header linking to home.

### ISSUE THREAD

**Issue by NateNear** [Arun9739/Paryatana#32]
I noticed that clicking on the "Parytana" header does nothing. So, I would like to add a ref to "Home" page everytime a user clicks on it.
please allow me to do the addressed changes
![Issue3 2](https://user-images.githubusercontent.com/92938055/193585105-5388ec63-48aa-40e8-9871-3f1f8bb99562.PNG)

**Comment by kanishk6103** [comment]
i can do it

**Comment by Arun9739** [comment]
Go ahead @NateNear 
Show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@kanishk6103 Please look for other issues or create new issue.
Show your love by starring the repo 🌟
