### ISSUE TITLE
Enhancing the contact for tours section

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#323]
# Which feature you are going to add 
- I want a improvemnt on 'Contact for tours' section of contact page as it looks very old.

# Describe the solution you'd like
- You can add anything to enhance it and make it feel better.

# Screenshots
![image](https://user-images.githubusercontent.com/84305637/197546370-99a82311-ac5d-46ab-ac13-02f52194fd57.png)

**Comment by zaahmed-nisum-com** [comment]
@Arun9739  can i work on it please?

**Comment by Arun9739** [comment]
@zaahmed-nisum-com Go ahead
Star 🌟 the repo to show your support.
