### ISSUE TITLE
Bugs in special packages

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#324]
# What is the bug :
- The dates in the special packages cards of our tours is not proper.
- The stars in the same cards are looking very odd.

# Expected behavior :
- Need to add proper dates and stars over there

# Screenshots :

![image](https://user-images.githubusercontent.com/84305637/197548515-11c4ed95-e6bd-41b0-8c14-928e41a4a653.png)

**Comment by ihtishamKhan** [comment]
@Arun9739 Please assign it to me, I will add random dates every time page loads also same for star rating

**Comment by Arun9739** [comment]
@ihtishamKhan Go ahead
Star the repo 🌟 to show your support

**Comment by ihtishamKhan** [comment]
I am on it
