### ISSUE TITLE
TESTIMONIALS BUG 

### ISSUE THREAD

**Issue by Devrajsinh03** [Arun9739/Paryatana#327]
# What is the bug :
Container overflow

# Expected behavior :
Content should be covered in the container.

# Screenshots :
<img width="1440" alt="ed" src="https://user-images.githubusercontent.com/103804567/197786335-18bb77a3-6e11-44b3-b000-233548e999ab.png">

**Comment by Arun9739** [comment]
@Devrajsinh03 Go ahead
Plz star the repo 🌟 to show your support.

**Comment by Devrajsinh03** [comment]
@Arun9739 I have fixed this bug please check the PR
