### ISSUE TITLE
Want to add useful resources in contributing.md

### ISSUE THREAD

**Issue by Ultimateutkarsh11** [Arun9739/Paryatana#331]
# Which feature you are going to add 
In the contributing.md section, I want to add links to useful blogs, Youtube videos and GitHub repositories so that beginners do not face any difficulty while contributing.

# Screenshots
![image](https://user-images.githubusercontent.com/95978839/198680076-e3764880-0e3f-47ef-9139-6398483bf494.png)

**Comment by Arun9739** [comment]
@Ultimateutkarsh11 Go ahead
Plz star the repo 🌟 to show your support

**Comment by Ultimateutkarsh11** [comment]
Sure, I starred the repository.
Thanks for assigning!
