### ISSUE TITLE
Favicon not visible at the home page

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#332]
# What is the bug :
- The favicon not visible at the home page due to the some problem

# Expected behavior :
- Fix the issue do that the favicon is visble at home page same as visble at other pages.
- Same problem at the 'our tours' page need to be done.

# Screenshots :

**Comment by RashiSingh20** [comment]
I would like to work on this.

**Comment by issue31** [comment]
Will you please assign me this issue @Arun9739 .

**Comment by KanjiZain** [comment]
@Arun9739 Assign it to me will go easy way

**Comment by Arun9739** [comment]
@RashiSingh20 Go ahead
Plz star the repo 🌟 to show your support

**Comment by Arun9739** [comment]
@KanjiZain and @issue31 Thank you for your interest
But plz look for other issues or create new issues

Plz star 🌟 the repo to show your support.

**Comment by Arun9739** [comment]
@RashiSingh20 As the issue is fixed, it will be closed.
