### ISSUE TITLE
Logo placement is wrong

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#340]
# What is the bug :
- Logo at the navbar in all pages has been mispalced. The logo is not visble properly.

# Expected behavior :
- Logo needs to be visble properly.

# Screenshots :

![image](https://user-images.githubusercontent.com/84305637/198840864-81cb80c2-01ee-4f46-b8c3-22afbd2367ed.png)

**Comment by hokandil** [comment]
I would to like to work on this, please assign it to me

**Comment by Arun9739** [comment]
@hokandil Go ahead
Star the repo 🌟 to show your support.
