### ISSUE TITLE
Improving 'what we do' section

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#341]
# Which feature you are going to add 
- The 'what we do' in about page doesn't have some proper information. 

# Describe the solution you'd like
- Need some proper sub-title, content, and image to describe about 'Paryatana' website services.
- You can change that section's format also if you have any best idea.

# Screenshots

![image](https://user-images.githubusercontent.com/84305637/198841377-73bf9da8-a2c2-4998-9d08-4a9fd78bfb7f.png)

**Comment by Arun9739** [comment]
@Priyanshu-su30 Go ahead
Plz star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@Priyanshu-su30 Plz finish your task early

**Comment by inderharrysingh** [comment]
@Arun9739  assign this issue to me
