### ISSUE TITLE
Adding links to 'contact for tours' section

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#342]
# What is the bug :
- There is no proper social media links in the 'contact for tours' of contact page.

# Expected behavior :
- Need to add just the proper links of that social medias.
- No need to add the link for particular social media account.

# Screenshots :

![image](https://user-images.githubusercontent.com/84305637/198841773-44713800-e422-42af-b276-14ea0583798b.png)

**Comment by AnonymousSudh** [comment]
assign me this.. I will complete it within 10 min.

**Comment by Arun9739** [comment]
@AnonymousSudh Go ahead
Star the repo 🌟 to show your support.
