### ISSUE TITLE
Adding different images at 'welcome to paryatana'

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#345]
# Which feature you are going to add 
- The images in slideshow are same across all the 4 slides.

# Describe the solution you'd like
- Need a different images at differnt slides so as to enhance the view.
- You can put the images which best suits the content.

# Screenshots

![image](https://user-images.githubusercontent.com/84305637/198870920-1ba25b52-183d-4c58-8a1b-323ef146aded.png)

**Comment by pratik2315** [comment]
Hey @Arun9739 I would like to work on this issue if its alright

**Comment by Arun9739** [comment]
@pratik2315 Go ahead
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@pratik2315 Plz finish your task early
