### ISSUE TITLE
Footer Email contact 

### ISSUE THREAD

**Issue by Devrajsinh03** [Arun9739/Paryatana#347]
Footer contact via Email section is not matching with website Ui theme and felt bit off.

<img width="1440" alt="Screenshot 2022-10-31 at 10 04 21 AM" src="https://user-images.githubusercontent.com/103804567/198932433-49dd7a09-dff5-4198-8cf8-3b8f273c3b3e.png">

**Comment by logicalahara** [comment]
@Devrajsinh03, would love to contribute to this for making design changes to match website theme.

#### Will you please assign this to me and add 'hacktoberfest' label to this issue ?

**Comment by Arun9739** [comment]
Go ahead @Devrajsinh03 
Star the repo 🌟 to show your support.

**Comment by Arun9739** [comment]
@logicalahara Thanks for the interest
But this issue is already been assigned to someone else.
Plz look for other issues or create new issues

Plz star the repo 🌟 to show your support.
