### ISSUE TITLE
Responsive Header

### ISSUE THREAD

**Issue by kushaljgec2025** [Arun9739/Paryatana#348]
# Which feature you are going to add 
![problem](https://user-images.githubusercontent.com/108950724/198935246-283e770a-ca1a-4be8-a56d-fc01ffb9b8a7.png)

# Describe the solution you'd like
responsive useing media query

# Screenshots

**Comment by Arun9739** [comment]
@kushaljgec2025 Go ahead
Star the repo 🌟 to show your support.
