### ISSUE TITLE
Update Hero.css and readme.md

### ISSUE THREAD

**Issue by sb-decoder** [Arun9739/Paryatana#350]
# Which feature you are going to add 
update readme.md and hero.css

# Describe the solution you'd like
added color and font family to description in landing page and  curved the button of discover and play

# Screenshots
![Screenshot 2022-10-31 123848](https://user-images.githubusercontent.com/108983339/198952018-caa2f92e-4a48-40e1-b489-7b0d650f29d6.png)

**Comment by Arun9739** [comment]
@sb-decoder Go ahead 
Star the repo 🌟 to show your support.

**Comment by sb-decoder** [comment]
I have already made a PR. Please check.
