### ISSUE TITLE
improve mobile view by making more responsive 

### ISSUE THREAD

**Issue by shyamtawli** [Arun9739/Paryatana#357]
# What is the bug :
Footer is not mobile friendly and card are not well maintained

# Expected behavior :
Should be all device freindly.

# Screenshots :
![op](https://user-images.githubusercontent.com/104145978/209553656-70ee0bf3-7407-4c70-b2fa-8c0eb5721b60.JPG)

**Comment by shyamtawli** [comment]
i can work on this.. please assign me.

**Comment by Arun9739** [comment]
@shyamtawli Go ahead
Plz star the repo ⭐ to show your support.

**Comment by shyamtawli** [comment]
@Arun9739 already done. Check my PR.

**Comment by shyamtawli** [comment]
@Arun9739 you can close these issue.
