### ISSUE TITLE
Adding a back end for managing the tourist destinations

### ISSUE THREAD

**Issue by Nick-surferboy** [Arun9739/Paryatana#365]
# Which feature you are going to add 
In order to manage the tourist destinations, adding, updating,deleting destinations, we could create a backend app for storing and retrieving destinations.
Then the front end could communicate with back end for displaying the tourist destinations

# Describe the solution you'd like
- A admin login page
- A destination managing page
- Using a database, such as mongo DB or Firebase

# Screenshots

**Comment by Arun9739** [comment]
@Nick-surferboy Go ahead
Star the repo ⭐ to show your support.
