### ISSUE TITLE
Hero Section in Mobile Layout Can be Improved

### ISSUE THREAD

**Issue by SujalSamai** [Arun9739/Paryatana#37]
**Is your feature request related to a problem? Please describe.**
Currently the hero section in each page of website looks very small to make a proper impact on the visitors of the website. This can be improved with better height and readability added in these sections.
**Describe the solution you'd like**
I would like to increase the height of the hero section, so that it can create an impact on the visitors. Also in certain images, readability of font is very less, I would like to improve that too.
**Screenshots**
![image](https://user-images.githubusercontent.com/87236576/193606908-b5eba874-0ab9-494a-bc8f-4def0d2993f9.png)
![image](https://user-images.githubusercontent.com/87236576/193606953-f05abf2e-d407-4fb4-a90d-d38790ea2968.png)

**Comment by Arun9739** [comment]
@SujalSamai Go ahead !!
Show your support by stargazing the repo 🌟

**Comment by Arun9739** [comment]
@SujalSamai Plz finish the task early

**Comment by Arun9739** [comment]
@SujalSamai Due to no proper activity this issue will be closed
