### ISSUE TITLE
Adding functionality to learn more button

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#4]
**Is your feature request related to a problem? Please describe.**
- The "Learn more" button should be functional after clicking it

**Describe the solution you'd like**
- Make the button such that after clicking the button it should go to tours and special packages section.
- Read the content above the learn more secion and change according to functionality.
- You can link other website too after clicking the button.
- Maintain the style of the project.
- Change all 3 "Learn more" buttons present in different pages such as home, about etc.

**Screenshots**

![image](https://user-images.githubusercontent.com/84305637/193541844-10c57b98-c597-46fb-8c4c-f04f25a5444d.png)

**Comment by Swastik1710** [comment]
Hey, I'd love to work on this issue. Kindly assign it to me.

**Comment by amanchoudhary18** [comment]
I believe I can work on this feature quite well. I would love to be assigned to this task.

**Comment by abhishekpatil4** [comment]
@Arun9739 Assign me this issue. I'm a full-stack developer (MERN Stack). HTML CSS JS NodeJs ExpressJs Bootstrap Figma Tailwindcss

**Comment by Arun9739** [comment]
Go ahead @Swastik1710 
Show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@amanchoudhary18 and @abhishekpatil4 thank foryour interest
Please create another issue or look for other issue 😃

**Comment by Swastik1710** [comment]
> Go ahead @Swastik1710 Show your love by starring the repo 🌟

Sure @Arun9739, thanks for assigning.
