### ISSUE TITLE
Overall navbar improvements

### ISSUE THREAD

**Issue by kanishk6103** [Arun9739/Paryatana#41]
*What is the bug**
The navbar looks very basic, it needs to be improves so that it looks more presentable.

**Expected behavior**
Making it look visually more appealing and adjusting height of the elements.

**Comment by kanishk6103** [comment]
So, i wanted to add a little styling to the navbar so that it looks better and more visually appealing.

**Comment by Arun9739** [comment]
@kanishk6103 Thank you for your interest
But the navbar issue is already present and has been assigned to someone else
Please look for other issues or create new issues

Show your support by starring the repo 😄
