### ISSUE TITLE
UI improvements and Styling

### ISSUE THREAD

**Issue by Z3RO-O** [Arun9739/Paryatana#44]
*A particular color theme should be followed all over.
** divs are coinciding with the carousel and color combinations can be improved box shadow can be added to each box.
*** better fonts can be used.

**Comment by Z3RO-O** [comment]
Please assign this issue to me

**Comment by Arun9739** [comment]
@Z3RO-O go ahead
Show your support by staring the repo 🌟

**Comment by Z3RO-O** [comment]
ok
