### ISSUE TITLE
Add a cool CSS effect or an image near Contact Us form. 

### ISSUE THREAD

**Issue by RathoreAbhiii** [Arun9739/Paryatana#46]
**Is your feature request related to a problem? Please describe.**

The left side of the form on the Contact page looks empty and does not give a good look to the aesthetics of the website.

**Describe the solution you'd like**

I would like to add a cool CSS effect or an image that keeps in check with the aesthetics of the website. 

**Screenshots**
![Screenshot-101](https://user-images.githubusercontent.com/91001195/193639135-3c43df48-2fbd-4682-b9a2-6bc81be8f028.png)

**Comment by RathoreAbhiii** [comment]
@Arun9739 Could you please assign me this issue? I would like to work in it. Thanks!

**Comment by Arun9739** [comment]
@RathoreAbhiii there is one google map at that place.
Please fix that map instaed of adding a image.
Put a location of any place in INDIA

Show your support by starring the repo 🌟

**Comment by RathoreAbhiii** [comment]
> @RathoreAbhiii there is one google map at that place. Please fix that map instaed of adding a image. Put a location of any place in INDIA
> 
> Show your support by starring the repo star2

Alright! Will try my best.

**Comment by RathoreAbhiii** [comment]
I have fixed the map and added a pointer as well, the CSS for the map can be customised as suited. The PR still has some merge conflicts, since I am new to Open Source, I hope you understand and I don't think that should be a big problem. Please review the PR and merge it at the earliest! I had a great time working on this issue as I really learned a lot of things. Thanks!
