### ISSUE TITLE
Create a Blog Section for Paryatana

### ISSUE THREAD

**Issue by prathimacode-hub** [Arun9739/Paryatana#49]
**Is your feature request related to a problem? Please describe.**
Adding a blog section will be a go-to inspiration for travelers to come out of their comfort zone

**Describe the solution you'd like**
Inclusion of blog section will make things easier for explorers to get a predefined insights on travel information on visa, flights, restrictions, useful information, making navigation easier and many more.

Can you assign this issue to start working? @Arun9739

**Comment by Arun9739** [comment]
Go ahead @prathimacode-hub 
Good idea 👍 

Show your support by starring the repo 🌟

**Comment by Arun9739** [comment]
@prathimacode-hub Plz finish the task early

**Comment by prathimacode-hub** [comment]
Yes @Arun9739. Will get it done in a day.

**Comment by Arun9739** [comment]
@prathimacode-hub Due to inactivity this issue will be closed.

**Comment by prathimacode-hub** [comment]
@Arun9739, I will be doing it. Can you reopen the issue?
