### ISSUE TITLE
Adding dark mode feature

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#5]
**Is your feature request related to a problem? Please describe.**
- Add a dark mode fature to all pages present in a web page

**Describe the solution you'd like**
- You should not discard any component of web page.
- You have to make sure that fonts and colors appear correctly

**Screenshots**

**Comment by zainbinfurqan** [comment]
@Arun9739  I would like to work on it, 
Solution: I will create a config obj and will store it on local storage and will create a util function which will add dark/light mode on web pages.

**Comment by Arun9739** [comment]
Great solution @zainbinfurqan !!
Go ahead !!
Showcase you love by starring the repo !!

**Comment by Arun9739** [comment]
@zainbinfurqan Please finish your task early, else it will be reassigned to someone else.

**Comment by zainbinfurqan** [comment]
@Arun9739 working on it.

**Comment by zainbinfurqan** [comment]
You can assign this to any other,

**Comment by Arun9739** [comment]
Anyone can take up this issue

**Comment by Aarav238** [comment]
Plesse assign this to me @Arun9739  .
I can complete it as soon as you will assign

**Comment by Arun9739** [comment]
@Aarav238 This issue was proposed by someone else and it's assigned to him
Plz look for other issue or create new issues.
Star the repo 🌟 to show your support
