### ISSUE TITLE
Would like to work on the structuring and documentation of the project 

### ISSUE THREAD

**Issue by ShrutiMishra-2002** [Arun9739/Paryatana#50]
The core of a project is documentation through which people get to know about a particular project .
As the project is not having a proper documentation i would like to work on it .
Kindly assign it to me @Arun9739

**Comment by Arun9739** [comment]
@ShrutiMishra-2002 Go ahead
Make a prooper structured documentation

Show your love by starring the repo 🌟

**Comment by Arun9739** [comment]
@ShrutiMishra-2002 Plz finish the task early

**Comment by Arun9739** [comment]
@ShrutiMishra-2002 Due to inactivity this issue will be reassigned.
Anyone can take up this issue

**Comment by ShrutiMishra-2002** [comment]
@Arun9739 can you assign it again due to my exams I was not able to do the work!

**Comment by Arun9739** [comment]
@ShrutiMishra-2002 A last chance will be given to you
Plz make it ASAP.

**Comment by Arun9739** [comment]
@ShrutiMishra-2002 Due to inactivity this issue will be closed.
