### ISSUE TITLE
Improve styles nav header

### ISSUE THREAD

**Issue by cTahirih** [Arun9739/Paryatana#58]
The header has a few mistakes in mobile like a on scroll only de menu hamburger is fixed .
![image](https://user-images.githubusercontent.com/32286691/193660321-b4964f6d-6926-4282-a10a-e8f52cc87d7c.png)
in desktop de menu nav is not aligned 
![image](https://user-images.githubusercontent.com/32286691/193660573-6ade23a7-57a9-4633-8f53-38a63bfbd4fb.png)

**Expected behavior**
The menu in mobile and desktop should be fixed to facilitate to the user the navigation in the web

**Comment by cTahirih** [comment]
I can take this issue

**Comment by Arun9739** [comment]
@cTahirih The nav bar in desktop view is almost fixed by someone else.
Please do check it once.
You can try to improve mobile view.

Show your support by by starring the repo 🌟

**Comment by Arun9739** [comment]
@cTahirih plz finish the task early
Thank you 👍

**Comment by cTahirih** [comment]
Sorry for the delay, I already have the changes. i'm uploading it now.

**Comment by Arun9739** [comment]
@cTahirih The issue you mentioned is already resolved by other user.
Plz create new issue or look for other issues.
Thank you 👍
