### ISSUE TITLE
Add Preloader and Favicon to the Website

### ISSUE THREAD

**Issue by Pargat-Dhanjal** [Arun9739/Paryatana#59]
**Is your feature request related to a problem? Please describe.**
The website currently has no Favicon or Preloader. Many Modern Websites have this functionality.

**Describe the solution you'd like**
I would like to add a Preloader and a Favicon which Matches the current theme and purpose of the website

**Screenshots**
<img width="155" alt="Screenshot 2022-10-04 at 2 16 17 AM" src="https://user-images.githubusercontent.com/54456304/193679170-1215952d-5252-4f76-b1e1-c568634777c1.png">

**Comment by Arun9739** [comment]
@Pargat-Dhanjal just add the preloader
Adding favicon is assigned to someone else 

Show your love by starring the repo 🤩
