### ISSUE TITLE
Images in Popular packages of Home page

### ISSUE THREAD

**Issue by pandeatul27** [Arun9739/Paryatana#62]
*What is the bug**
The images to respective places mentioned in the popular packages are irrelevant.
**Expected behavior**
I can add relevant images to it
**Screenshots**
<img width="960" alt="2022-10-04 (5)" src="https://user-images.githubusercontent.com/94844506/193746978-ee158b5a-855d-4bf6-9982-0ceceebd4980.png">
**Additional context**

**Comment by pandeatul27** [comment]
Allow me to work on this issue under hacktoberfest

**Comment by Arun9739** [comment]
Go ahead @pandeatul27 
Show your support by starring the repo 🌟
