### ISSUE TITLE
Making Logo clickable and no Home button on other pages

### ISSUE THREAD

**Issue by MridulTi** [Arun9739/Paryatana#67]
## Is your feature request related to a problem? Please describe.**
I have seen that the logo of the website change color on hover but does not switch back to the home page on click
#### A clear and concise description of what you want to happen.
For this, I would like to make the Logo clickable so that on clicking it the page change to Home page, and to make it more effective I would like to remove the Home button from the Navbar on pages other than the index.html
**Screenshots**
![image](https://user-images.githubusercontent.com/92802892/193835733-b686b3d3-6f21-4db5-94d5-a29e24513e74.png)
Some thing Like this
![image](https://user-images.githubusercontent.com/92802892/193836323-2bc63ee9-ec84-4266-9c76-d0d7428ca2fb.png)

If you like the Idea then please assign this Issue to me!

**Comment by Arun9739** [comment]
Go ahead @MridulTi 
Good idea 👍 
Plz star the repo to showcase your love 🤩
