### ISSUE TITLE
Add Indian rupees symbol instead of dollor symbol

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#69]
**Is your feature request related to a problem? Please describe.**
- You need to add Indian rupees symbol wherever Dollar symbol is there.

**Describe the solution you'd like**
- Change all the dollor symbols to Rupee symbol.
- Change the price also accordingly(put any approximation value)

**Screenshots**

![image](https://user-images.githubusercontent.com/84305637/193867702-13777cac-caef-4bd6-8695-0ed63ad7892a.png)

**Comment by najeebkp** [comment]
hi @Arun9739  please assign me

**Comment by AnkitaMalik22** [comment]
i would love to work on this issue. please assign me !

**Comment by Arun9739** [comment]
@najeebkp Go ahead
Please star the repo ⭐ to show your support.

**Comment by Arun9739** [comment]
@AnkitaMalik22 look for other issue or create new issues
Please star the repo to show your support 🤩
