### ISSUE TITLE
Adding proper content to the tours section

### ISSUE THREAD

**Issue by Arun9739** [Arun9739/Paryatana#7]
**Is your feature request related to a problem? Please describe.**
- There are total four tours are present in "Our toors" section, you need to add proper content to it.

**Describe the solution you'd like**
- Change the Lorem content to the content according to the title.
- Fit the content in the box provided.
- Content should be about describing the place.
- Also make the dates unique for each tour.

**Screenshots**
![image](https://user-images.githubusercontent.com/84305637/193546931-2f5292b9-effb-4acc-ab42-848556d95f5c.png)

**Comment by Swastik1710** [comment]
Hey, can you please assign this issue to me, I'd love to work on this.

**Comment by Sidd2024** [comment]
Hello!, @Arun9739 I would like to work on this issue.
Solution: Replace lorem ipsum text with short description of place and provide unique dates. All this with some CSS icons

**Comment by JadugarKalakaboola** [comment]
Hi I would like to work on this issue.
I am planning to remove the dates and instead adding **Starting from: 22 March 2022**.
We can search about the places on internet and get Infos.
We can also add a **register now** button in the tour cards.

**Comment by ojninja16** [comment]
Hi @Arun9739..  i would like to work on this.....
adding more relevant images and content rather than

**Comment by abhishekpatil4** [comment]
@Arun9739 Assign me this issue. I'm a full-stack developer (MERN Stack). HTML CSS JS NodeJs ExpressJs Bootstrap Figma Tailwindcss

**Comment by Arun9739** [comment]
Go ahead @Sidd2024 
Show your love by starring the repo 🤩

**Comment by Arun9739** [comment]
@abhishekpatil4, @JadugarKalakaboola and @ojninja16 please look for other issues or create new issues.
Show your love by starring the repo 🌟
