### ISSUE TITLE
Improving Footer

### ISSUE THREAD

**Issue by Rashmisingh-18** [Arun9739/Paryatana#74]
*What is the bug**
Improving the footer, fixing those social media icons in the footer.

**Expected behavior**
Want to add services , contact, and social media icons in footer
![Parytana - Contact and 9 more pages - Personal - Microsoft​ Edge 04-10-2022 9 57 37 PM](https://user-images.githubusercontent.com/90052358/193874806-2e6a5a63-f00c-4cdc-a4d6-004eb5d213b0.png)

**Screenshots**

**Additional context**

**Comment by Rashmisingh-18** [comment]
> _What is the bug_* Improving the footer, fixing those social media icons in the footer.
> 
> **Expected behavior** Want to add services , contact, and social media icons in footer ![Parytana - Contact and 9 more pages - Personal - Microsoft​ Edge 04-10-2022 9 57 37 PM](https://user-images.githubusercontent.com/90052358/193874806-2e6a5a63-f00c-4cdc-a4d6-004eb5d213b0.png)
> 
> **Screenshots**
> 
> **Additional context** Add any other context about the problem here.

Please assign this issue to me under Hacktoberfest 2022.

**Comment by asphalke07** [comment]
I can do it too.
Till now i have solved 2 issues of this Repository, So i have good knowledge of my Tech Stack and Github contribution.

**Comment by Arun9739** [comment]
Thank you @asphalke07 and @Rashmisingh-18 for your interest
But this issue is alreday present and  has been assigned to someone else
Please create new issue or look for other issues presesnt.

Star the repo 🌟  to show your support.
