### ISSUE TITLE
NavBar acts differently in different pages on smaller devices.

### ISSUE THREAD

**Issue by Swastik1710** [Arun9739/Paryatana#80]
*What is the bug**
The NavBar doesn't show the home link on other pages and it is placed differently on other pages than the home page. This happens on smaller devices screen.
**Expected behavior**
The navbar should be seen at the same place on all pages and all devices.
**Screenshots**
![image](https://user-images.githubusercontent.com/71871571/193919356-7035e8d0-ab9a-4e37-a11f-fff5c2492d7a.png)

![image](https://user-images.githubusercontent.com/71871571/193919562-aaad27de-26a2-4795-8730-8cb425094154.png)

**Additional context**

**Comment by Swastik1710** [comment]
I'd like to work on this issue, kindly assign it to me.

**Comment by Arun9739** [comment]
@Swastik1710 Go ahead
Star he repo to show your love 🌟
