### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [Arun9739/Paryatana#88]
**Is your feature request related to a problem? Please describe.**

Hello! I think it would increase the interactivity of your website if you add comment section in addition to testimonials so as other people can read that feedback or can question them in that comment (nested comment)
**Describe the solution you'd like**
I can add comment section that would go with testimonial card so as to get more audience and visually attracting.
**Screenshots**
![image](https://user-images.githubusercontent.com/110082824/194012117-818a05bc-e5a3-45bb-91c6-a22aae71b981.png)

**Comment by aparna03dubey** [comment]
I want to contribute , please assign this to me.

**Comment by Arun9739** [comment]
Go ahead @AryanSahoo-2003 
Design the comment section as you feel the best
Show your support by stargazing the repo 🌟

**Comment by Arun9739** [comment]
@aparna03dubey Please look for other issues or create new issues
Show your support by starring the repo ⭐

**Comment by AryanSahoo-2003** [comment]
Sir, also in "Contact " page, left hand side is a bit empty which I don't know why but I think it should be filled up with some video or gif or photos...Could you check that if I can open new pull request and resolve that?
