### ISSUE TITLE
Improve header

### ISSUE THREAD

**Issue by Alam9835** [Arun9739/Paryatana#89]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Screenshots**
I want to improve the UI of the header section.

**Comment by aishwarya1735** [comment]
Can this issue be assigned to me?

**Comment by Arun9739** [comment]
Go ahead @aishwarya1735 
Show your support by starring the repo 🌟

**Comment by Arun9739** [comment]
@aishwarya1735 Plz look for other issues or create new issues
Show you support by stargazing the repo 🌟

**Comment by Alam9835** [comment]
i have done the changes please merge my PR #126

**Comment by Alam9835** [comment]
I have made the changes for issue #89

**Comment by Alam9835** [comment]
my PR #144

**Comment by Arun9739** [comment]
Anyone who want to work on this issue can take up.

**Comment by creater-shikha** [comment]
can you assign me this issue

**Comment by Arun9739** [comment]
@creater-shikha Go ahead
Star the repo ⭐ to showcase your love.

**Comment by creater-shikha** [comment]
I  resolve the issue, can you help me how to create a pull request
