### ISSUE TITLE
[Others] Proper catchlines for 'POPULAR PACKAGES' section

### ISSUE THREAD

**Issue by itsEobard2025** [Arun9739/Paryatana#9]
Hi Arun, it seems that the Packages section can use some proper content for various places(Kashmir/Kedarnath/etc)
<br/>
![image](https://user-images.githubusercontent.com/88548999/193551966-31efe56e-bb98-4e50-a9fd-35dbc79506b1.png)
 
- Do I want to work on this Issue ? 
> Yes
- Any other information I want to tell ?
> Alongside this I was also thinking to work on the CSS part(border/radius primarily) for the Cards given

![image](https://user-images.githubusercontent.com/88548999/193553300-b7cae034-e37f-4701-9ba0-667018a8092c.png)

**Comment by Arun9739** [comment]
Go ahead @itsEobard2025 
Great idea 🤩 
Show your ❤️ by starring the repo.

**Comment by Arun9739** [comment]
@itsEobard2025 Try to finish your task early.

**Comment by itsEobard2025** [comment]
Thanks for reminding me, you can check the PR whenever free 😄
