### ISSUE TITLE
Improving navbar

### ISSUE THREAD

**Issue by sumitkr2000** [Arun9739/Paryatana#92]
Hey @Arun9739 I want to improve the navbar of your website. I want to add icons and also the right part of navbar is not aligned to the page which is looking odd. I can fix it. Can you please assign me this issue. Thank you!

![Screenshot (355)](https://user-images.githubusercontent.com/100675296/194054533-54ccaaba-bc83-4286-b495-9350e0dc5519.png)

**Comment by Anurag-Singh-04** [comment]
Hey @Arun9739 I have made some changes in the navbar, hope you like it.
Before : 
<img width="1440" alt="Screenshot 2022-10-05 at 8 53 22 PM" src="https://user-images.githubusercontent.com/97782687/194099904-ce44d544-2fdd-4a74-b0bf-69f8b0bac83b.png">

After : 
<img width="1440" alt="Screenshot 2022-10-05 at 8 53 07 PM" src="https://user-images.githubusercontent.com/97782687/194100002-483df41d-1bc4-4956-9e0f-e83f0b287862.png">

Can you please assign this issue to me.

**Comment by Arun9739** [comment]
Go ahead @sumitkr2000 
Show your support by starring the repo ⭐

**Comment by Arun9739** [comment]
@Anurag-Singh-04 Plz look for other issues or create new issues
Show your support by starring the repo 🌟

**Comment by sumitkr2000** [comment]
@Arun9739 Thank you for approving

**Comment by Arun9739** [comment]
@sumitkr2000 Finish your task early

**Comment by sumitkr2000** [comment]
@Arun9739 I have already done this task...you can close this issue now.

**Comment by Arun9739** [comment]
@sumitkr2000 OK thanks :)
