### ISSUE TITLE
Improving the Navbar and Contact page

### ISSUE THREAD

**Issue by MayaSatishRao** [Arun9739/Paryatana#93]
**What is the bug**
Navbar in About,  Contact and Our tours page does not have home in the navbar. The form in the Contact page is not centered.

**Expected behavior**
Navbar should remain the same in all pages and form must be centered.
![g2](https://user-images.githubusercontent.com/67920373/194055830-11f8fe35-6787-4d8a-9e4d-0cf601999745.png)
![g3](https://user-images.githubusercontent.com/67920373/194055838-bb88edad-4466-47f5-b735-282e41f6b54b.png)
![g1](https://user-images.githubusercontent.com/67920373/194055842-306da20e-e335-429a-99ff-a72c357ae161.png)

**Comment by Arun9739** [comment]
@MayaSatishRao This issue is alreday present and has been assigned to someone else
Plz create new issues or look for other issues
Show your support by starring the repo 🌟
