### ISSUE TITLE
Smooth Animation

### ISSUE THREAD

**Issue by Naushad-dev** [Arun9739/Paryatana#97]
https://user-images.githubusercontent.com/106610708/194085955-36eda083-cc5e-443a-8523-e1c976689251.mp4
Hello, hope you are well I would like to contribute to this project by making this animation in the **WHO WE ARE section** more smooth which will make UI look better.
Thank you for your time.😊

**Comment by Arun9739** [comment]
Go ahead @Naushad-dev 
Star the repo 🌟 to showcase your love
