### ISSUE TITLE
Add favourite Place Section

### ISSUE THREAD

**Issue by AnkitaMalik22** [Arun9739/Paryatana#99]
**Is your feature request related to a problem? Please describe.**
Add favourite Place Section

**Describe the solution you'd like**
create a new nav link that shows the places you liked

**Screenshots**
![Screenshot (81)](https://user-images.githubusercontent.com/80139836/194092464-8c96c70a-1e6b-43bc-ad2b-3619663beff8.jpeg)

**Comment by Arun9739** [comment]
@AnkitaMalik22 Go ahead !!
Star the repo 🌟 to showcase your love
